### ISSUE TITLE
Dotnetty Client

### ISSUE THREAD

**Issue by hoangtrongphuc** [Azure/DotNetty#104]
Is Dotnetty compatible with .NET 3.5 (unity use .Net 3.5) ?
How to connect with server with other language ? (example : C++)

**Comment by avatar29A** [comment]
> How to connect with server with other language ? (example : C++)

If your server uses Tcp\Ip, you should use TcpSocketChannel.

**Comment by hoangtrongphuc** [comment]
Thank @avatar29A, Is TcpSocketChannel library ? U can provide any source or implement of this ?

**Comment by avatar29A** [comment]
@hoangtrongphuc, No, it's part of DotNetty. You could see this example https://github.com/Azure/DotNetty/tree/dev/examples/Echo.Client, it's simple tcp\ip client. For work with your server, you should write your own custom ChannelHandlerAdapter (as here https://github.com/Azure/DotNetty/blob/dev/examples/Echo.Client/EchoClientHandler.cs).

**Comment by hoangtrongphuc** [comment]
Echo.Client use lib from Dotnetty :  
```
using DotNetty.Buffers;
using DotNetty.Transport.Channels;
```
but I want to know How to connect with server in C++ or Nodejs (Client SDK for C++ or nodejs) ? I dont want rewrite Client lib to connect with Dotnetty.

**Comment by PBeckerr** [comment]
You can connect from any language/platform that support TCP.

**Comment by nayato** [comment]
@hoangtrongphuc we have no plans supporting .NET versions earlier than 4.5. You can try building DotNetty from source but even if that succeeds we cannot guarantee it will be maintained going forward.
