### ISSUE TITLE
ServerBootstrap throws upon attempting to bind to DnsEndpoint

### ISSUE THREAD

**Issue by Aaronontheweb** [Azure/DotNetty#110]
Similar to what we do in `Bootstrap`, we need to resolve a `DnsEndpoint` into an `IPEndPoint` before passing it down to an underlying `TcpSocketServerChannel`, as the `BindAsync` method implemented there won't accept anything that isn't an `IPEndPoint`.

`AbstractBoostrap` supports binding to `DnsEndpoints` currently but just doesn't do the extra step of resolving it yet.

**Comment by nayato** [comment]
What's the use case for this? You bind on address that is local to this machine. DNS resolution will return publicly assigned address which in some cases might not be the right thing to bind to.

**Comment by Aaronontheweb** [comment]
@nayato every time I've seen this feature used it's been for binding to `localhost` for testing purposes.

**Comment by Aaronontheweb** [comment]
also seen it used on scenarios where testing across multiple VMs with local host definitions (because it was easier to do that than force everyone on the team to map identical IPs for local cluster testing) - personally tested a lot of our work with production distributed actor systems that way, but that's an outlier.

**Comment by nayato** [comment]
I see more potential for confusion rather than value from this. Better know what you're supposed to bind to in conformance to what client will bind to.
For dynamic scenarios like mentioned - do DNS resolution upfront.
I do agree though that current state is not ideal either causing confusion as to what's acceptable to pass vs what is not.

**Comment by Aaronontheweb** [comment]
> I see more potential for confusion rather than value from this.

From personal experience supporting an OSS library like this for several years, this is not true. People are going to bind to localhost and complain that it doesn't work. I'd just make it work rather than add friction to the process. Doesn't matter if it's right or wrong in principle, it's right in practice.

**Comment by nayato** [comment]
That's what I'm calling out as confusing in current API. In Java there's `SocketAddress` that is clearly NOT accepting DNS names. In .NET there's `IPAddress` but that is rather restrictive (not at present of course) and there is `EndPoint` which is a base class for `DnsEndPoint` as well and that's where the confusion comes from.

**Comment by Aaronontheweb** [comment]
@nayato that makes sense - unfortunately for Akka.NET users I gotta support some semblance of backwards compat here, which is agnostic about domains versus IPs but I can do that at the application level.
