### ISSUE TITLE
port ObjectEncoder and ObjectDecoder

### ISSUE THREAD

**Issue by thijsa** [Azure/DotNetty#112]
It adds support to send and receive objects.

**Comment by Tochemey** [comment]
I will give it a try

**Comment by Frank591** [comment]
Is it actual issue? Want to try do that

**Comment by nayato** [comment]
In netty it relies on Java's built-in serialization. There isn't much value doing analogous impl in DotNetty and where needed, ProtoBuf can easily be used.
