### ISSUE TITLE
Port protobuf codec

### ISSUE THREAD

**Issue by huxiao5579144** [Azure/DotNetty#118]
How to apply ProtobufVarint32FrameDecoder, ProtobufVarint32LengthFieldPrepender, ProtobufEncoder?
Headache!!

public class ProtobufVarint32FrameDecoder extends ByteToMessageDecoder {

```
// TODO maxFrameLength + safe skip + fail-fast option
//      (just like LengthFieldBasedFrameDecoder)

@Override
protected void decode(ChannelHandlerContext ctx, ByteBuf in, List<Object> out) throws Exception {
    in.markReaderIndex();
    final byte[] buf = new byte[5];
    for (int i = 0; i < buf.length; i ++) {
        if (!in.isReadable()) {
            in.resetReaderIndex();
            return;
        }

        buf[i] = in.readByte();
        if (buf[i] >= 0) {
            int length = CodedInputStream.newInstance(buf, 0, i + 1).readRawVarint32();// CodedInputStream ...??
            if (length < 0) {
                throw new CorruptedFrameException("negative length: " + length);
            }

            if (in.readableBytes() < length) {
                in.resetReaderIndex();
                return;
            } else {
                out.add(in.readBytes(length));
                return;
            }
        }
    }

    // Couldn't find the byte whose MSB is off.
    throw new CorruptedFrameException("length wider than 32-bit");
}
```

}

**Comment by nayato** [comment]
what is the issue here? We do not have a port of protobuf codec, yes. Are you asking what is `CodedInputStream`? It is part of Protobuf library, also available in C# version: https://github.com/google/protobuf/blob/master/csharp/src/Google.Protobuf/CodedInputStream.cs. FYI, if you contemplate porting Protobuf codec, it would make sense to put it in a separate project/nuget package to avoid unnecessary reference to Protobuf when ppl just use LengthField* classes for example.

**Comment by StormHub** [comment]
I will be porting Protobuf.

**Comment by StormHub** [comment]
Initial Protobuf 3 codec

**Comment by StormHub** [comment]
I am wondering it is still valid to port Protobuf 2 support.

**Comment by StormHub** [comment]
It turns out I have to port Protobuf 2 (Google.ProtocalBuffers)

**Comment by huxiao5579144** [comment]
@nayato  cool, before this ,myCode is too large 
dotnetServer(netty) --->serializeC#Package--->googleJson--->DeserializeJavaPackage---> javaTerminal
                               <-------------------------request/response-------------------------->

now, use @StormHub determine if there are any that can be eliminated. 
and  encrypted transport
 has good way to recommend ? thanks very much

**Comment by StormHub** [comment]
@huxiao5579144 I am not sure what you mean
