### ISSUE TITLE
there some problems，when using in mac os x

### ISSUE THREAD

**Issue by zmyer** [Azure/DotNetty#124]
in mac os x，I use DotNetty in my Xamarin IDE，but there are some problems，such as:"this project type is not supported"，how to deal with such problems，can you give me some suggestions, thanks

**Comment by nayato** [comment]
@zmyer, I have no idea about Xamarin or what kind of projects it works with. We do not have immediate plans to support Xamarin IDE. We plan to add support for .NET Core (.NET Platform Standard 1.3) in coming weeks. We have no plans to support Mono directly (which I assume Xamarin runs on).
