### ISSUE TITLE
Support UWP/UAP

### ISSUE THREAD

**Issue by HakanL** [Azure/DotNetty#129]
I'm not sure what's involved, but it would be very nice to have DotNetty support UWP/UAP so this could be used on Windows 10 IoT. I'm not sure how much this related to .NET Core support/.NET Standard.

**Comment by nayato** [comment]
@HakanL, we have no plans to target UWP specifically. Last I checked there were a few rather inconvenient limitations that would result in either bloat of `#if`s or reduced performance. It is hard to track, but I believe there are plans to make UWP support .Net Platform Standard. DotNetty is on track to support .NET Platform Standard 1.3 (see [here](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md#mapping-the-net-platform-standard-to-platforms) for details).

**Comment by HakanL** [comment]
I see, so maybe there will be some resolution on what .NET Platform Standard UWP (UAP) will provide at some point, and at that point there may be more clarity how DotNetty would play UWP. At the moment I was trying to add DotNetty to my Win10Iot project, probably best for me to look elsewhere in the short term.
