### ISSUE TITLE
port Redis codec

### ISSUE THREAD

**Issue by nayato** [Azure/DotNetty#131]

**Comment by lucasallan** [comment]
I can give it a shot

**Comment by nayato** [comment]
@lucasallan, would be great to see this through!

**Comment by lucasallan** [comment]
What is the recommended environment to work on it? 

I'm trying to build it (and run tests) on OSx with mono, but so far it has been difficult.

**Comment by StormHub** [comment]
I am trying to port the Redis part because I need it for project in the near future. Forked and working in progress.

**Comment by StormHub** [comment]
@lucasallan Have you made any progress on this one? I really really really need it so badly.

**Comment by nayato** [comment]
@StormHub saw your fork - that's intense :+1:

**Comment by StormHub** [comment]
@nayato Almost there 👍

**Comment by StormHub** [comment]
#161 requested for initial full Redis implementation

**Comment by nayato** [comment]
Done through #161
