### ISSUE TITLE
Object Disposed Exception running EchoClient and EchoServer

### ISSUE THREAD

**Issue by GrahamDarnell** [Azure/DotNetty#133]
Run the EchoServer, run EchoClient, hit enter on EchoClient to close it down. The EchoServer throws ObjectDisposedException when attempting this.Socket.Receive() in TcpSocketChannel::DoReadBytes()

**Comment by nayato** [comment]
Known issue, will be fixed in an upcoming release. Also applies to `TlsHandler`.
