### ISSUE TITLE
IChannel‘s writeAndFlushAsync function can not work

### ISSUE THREAD

**Issue by zmyer** [Azure/DotNetty#138]
when using IChannel’s writeAndFlushAsync function to send request，it will return Task object which state is WaitingForActivation and IChannel object will lost，How can I deal with it，can you give me some suggestions，thanks you

**Comment by nayato** [comment]
@zmyer, what do you mean by "IChannel object will lost"? Channel is closed or ..? Task will transition to RanToCompletion, Canceled, or Faulted once it is processed by the channel. In case of channel closure, it will be Faulted with ChannelClosedException if it was still pending processing in outbound buffer. As to how to observe task status changes, please refer to https://msdn.microsoft.com/en-us/library/ff963556.aspx and https://msdn.microsoft.com/en-us/library/mt674882.aspx

**Comment by zmyer** [comment]
yeah, IChannel object closed by unexcepted, there are my some code segments, 
`                Task task = channel.WriteAndFlushAsync(request);
                task.ContinueWith(t =>
                {
                    if (t.IsCompleted)
                    {
                        responseFuture.setRequestOk(true);
                    }
                    else
                    {
                        ResponseFuture result;
                        responseFuture.setRequestOk(false);
                        responseTables.TryRemove(request.opaque(), out result);
                        responseFuture.setCause(task.Exception);
                        responseFuture.putResponse(null);
                        log.Warn("send a request command to channel <" + channel.RemoteAddress.ToString() + "> failed");
                        log.Warn(request.ToString());
                    }
                });
                
                RemotingCommand responseCommand = responseFuture.waitResponse(timeoutMills);`
when runing in waitResponse function, connection is closed and there is not any exception,how can i do deal with it, thanks

**Comment by zmyer** [comment]
yeah, IChannel object closed by unexcepted, there are my some code segments, 
``                Task task = channel.WriteAndFlushAsync(request);
                task.ContinueWith(t =>
                {
                    if (t.IsCompleted)
                    {
                        responseFuture.setRequestOk(true);
                    }
                    else
                    {
                        ResponseFuture result;
                        responseFuture.setRequestOk(false);
                        responseTables.TryRemove(request.opaque(), out result);
                        responseFuture.setCause(task.Exception);
                        responseFuture.putResponse(null);
                        log.Warn("send a request command to channel <" + channel.RemoteAddress.ToString() + "> failed");
                        log.Warn(request.ToString());
                    }
                });
                
                RemotingCommand responseCommand = responseFuture.waitResponse(timeoutMills);
when runing in waitResponse function, connection is closed and there is not any exception,how can i do deal with it, thanks

**Comment by zmyer** [comment]
yeah, IChannel object closed by unexcepted, there are my some code segments, 
`                Task task = channel.WriteAndFlushAsync(request);
                task.ContinueWith(t =>
                {
                    if (t.IsCompleted)
                    {
                        responseFuture.setRequestOk(true);
                    }
                    else
                    {
                        ResponseFuture result;
                        responseFuture.setRequestOk(false);
                        responseTables.TryRemove(request.opaque(), out result);
                        responseFuture.setCause(task.Exception);
                        responseFuture.putResponse(null);
                        log.Warn("send a request command to channel <" + channel.RemoteAddress.ToString() + "> failed");
                        log.Warn(request.ToString());
                    }
                });
                
                RemotingCommand responseCommand = responseFuture.waitResponse(timeoutMills);`
when runing in waitResponse function, connection is closed and there is not any exception,how can i do deal with it, thanks

**Comment by zmyer** [comment]
yeah, IChannel object closed by unexcepted, there are my some code segments

                Task task = channel.WriteAndFlushAsync(request);
                task.ContinueWith(t =>
                {
                    if (t.IsCompleted)
                    {
                        responseFuture.setRequestOk(true);
                    }
                    else
                    {
                        ResponseFuture result;
                        responseFuture.setRequestOk(false);
                        responseTables.TryRemove(request.opaque(), out result);
                        responseFuture.setCause(task.Exception);
                        responseFuture.putResponse(null);
                        log.Warn("send a request command to channel <" + channel.RemoteAddress.ToString() + "> failed");
                        log.Warn(request.ToString());
                    }
                });
                
                RemotingCommand responseCommand = responseFuture.waitResponse(timeoutMills);
when runing in waitResponse function, connection is closed and there is not any exception,how can i do deal with it, thanks

**Comment by nayato** [comment]
it isn't clear what `ResponseFuture.waitResponse` does. One possible explanation, if if it blocks execution and the code happens to run in event loop, it would prevent anything from happening in that loop -> channel closure will never even get processed completely let alone signaling of outstanding writes. That's a guess of course.

**Comment by zmyer** [comment]
er, there is waitResponse function code,and I find task status is waitingForActivation, the InEventLoop status is false,such code below maybe not running in event loop

` public RemotingCommand waitResponse(long timeoutMills)
        {
            this.latch.Wait((int)timeoutMills);
            return this.responseCommand;
        }`

**Comment by zmyer** [comment]
en, may I ask a question，how to use channel.writeAndFlushAsync? I find writeAndFlushAsync will return task object，may I need to wait such task object?

**Comment by nayato** [comment]
@zmyer, returned Task indicates when sending was "completed", i.e. dispatched to networking stack. You'd need to observe the result of sending (i.e. subscribing to task completion) at least to react in case of failure which might indicate closure of connection.
