### ISSUE TITLE
how to manage IByteBuffer lifetime properly?

### ISSUE THREAD

**Issue by egmkang** [Azure/DotNetty#139]
I'm using `DotNetty` writing codes to communicate with my c++ server. I read some blogs and realized `IByteBuffer` must be `release`. to confirm this and usage DotNetty in the right way, i have these questions:

- in my codec, do i need release the IByteBuffer?
```
public override void ChannelRead(IChannelHandlerContext context, object message)
{
    IByteBuffer buffer = message as IByteBuffer;
    //dost i need release this message after my useage
    buffer.release();
}
```
- i must release an IByteBuffer object allocated by myself?
```
IByteBuffer buffer1 = Unpooled.WrappedBuffer(array);
IByteBuffer buffer2 = UnpooledHeapByteBuffer(PooledByteBufferAllocator.Default, array, array.Length);
```
- interface IByteBuffer  supply many member return an IByteBuffer object. do i need release them?
```
IByteBuffer buff = (message as IByteBuffer).ReadBytes(128);
IByteBuffer slice = (message as IByteBuffer).ReadSlice(128);
```

**Comment by nayato** [comment]
@egmkang, please refer to [this](http://netty.io/wiki/reference-counted-objects.html) first. Extra comments on your questions (in order):
- yes if you do not plan to pass it forward either unchanged, wrapped in another object or in a form of derived buffer.
- WIth unpooled buffers there's not much benefit in explicitly releasing but if you ever plan to optimize for high-perf scenarios you would end up using pooled buffers as much as possible and having proper ref-counting practices in place from the beginning will be beneficial. Also, for high-perf, generally avoid using `ReferenceCountUtil.SafeRelease` in happy-path scenarios - it masks incorrect over-releasing and is really meant for exception-handling cases.
- these are derived buffers and they delegate ref-counting to an original buffer.

**Comment by egmkang** [comment]
@nayato thank you very much. i have read the article carefully. it have solved my No.2 and No.3 problems.  about the first problem. the article said i have release the buffer. 
my question is Netty always Allocate A New Buffer, it won't reuse the buffer object?
for example, when the buffer contains part of the whole message, i must cache the bytes of buffer netty allocated, and release the buffer, until i can decode one whole message.

https://github.com/Azure/DotNetty/blob/86749e908c1be0800ca43374102b28980519b7ba/src/DotNetty.Transport/Channels/Sockets/AbstractSocketByteChannel.cs#L101

**Comment by egmkang** [comment]
@nayato i found out ByteToMessageDecoder has finished the feature. thank you again.
