### ISSUE TITLE
Enable scheduling work items with 2 state parameters

### ISSUE THREAD

**Issue by nayato** [Azure/DotNetty#14]
To avoid allocations it is often useful to pass more than one object along with work item: this/self and piece of data to be processed. Such an option is available for immediate execution through IEventExecutor.Execute() overload but there's no corresponding version of .Schedule().

**Comment by Aaronontheweb** [comment]
Ah, ok - this explains my comments on #16 - would you mind adding this explanation in the comments somewhere on the `Schedule` methods?
