### ISSUE TITLE
MessageToMessageDecoder.cs : 59

### ISSUE THREAD

**Issue by egmkang** [Azure/DotNetty#141]
https://github.com/Azure/DotNetty/blob/dev/src/DotNetty.Codecs/MessageToMessageDecoder.cs#L34
https://github.com/Azure/DotNetty/blob/dev/src/DotNetty.Codecs/MessageToMessageDecoder.cs#L59

line 34 has release the object `message`, but line 59 use it again. so an exception occured.
i'm using `StringDecoder` write some samples, and found this problem.  i have delete line 59 for and the sample run well.

**Comment by nayato** [comment]
Thanks for reporting. call to base method is a mistake here. I will patch soon.

**Comment by nayato** [comment]
fixed in #142
