### ISSUE TITLE
IChannelHandlerContext objec lack of IEventExecutorGroup attribute

### ISSUE THREAD

**Issue by zmyer** [Azure/DotNetty#143]
In HandlerAdded function, there only an argument-IChannelHandlerContext , how to add an handler？ex：ctx.Channel.Pipeline.AddBefore(?)

**Comment by nayato** [comment]
talking about HandlerAdded - I assume you're within the channel handler so you can pass `this` to AddBefore in case you want to add another handler on HandlerAdded specifically.
