### ISSUE TITLE
Are there some plans to support HTTP/HTTP2.0

### ISSUE THREAD

**Issue by zmyer** [Azure/DotNetty#144]
Hello，In DotNetty develop plans，it will be supported HTTP/HTTP2.0? I want to use DoNetty to develop some applications which was used HTTP2.0, How can i to it with DotNetty？

**Comment by bobanco** [comment]
Hi @zmyer , there is no plans yet, but contributions are always welcome :smile:

**Comment by nayato** [comment]
in fact, I started porting HTTP 1.1 codec but it's quite a lot of work to see it through. Don't hold your breath for the next month or so.

**Comment by nayato** [comment]
also, we already have an issue to port the codec (#52) so closing this one.
