### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by webconfig** [Azure/DotNetty#145]
EventId : 4, Level : Warning, Message : , Payload : [source : DotNetty.Transport
.Channels.DefaultChannelPipeline] [message : An ExceptionCaught() event was fire
d, and it reached at the tail of the pipeline. It usually means the last handler
 in the pipeline did not handle the exception.] [exception : System.ObjectDispos
edException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size,
 SocketFlags socketFlags, SocketError& errorCode)
   at DotNetty.Transport.Channels.Sockets.TcpSocketChannel.DoReadBytes(IByteBuff
er byteBuf)
   at DotNetty.Transport.Channels.Sockets.AbstractSocketByteChannel.SocketByteCh
annelUnsafe.FinishRead(SocketChannelAsyncOperation operation)] , EventName : War
ningInfo, Timestamp : 2016-07-24T09:52:35.2307543Z, ProcessId : 7452, ThreadId :
 7288

EventId : 4, Level : Warning, Message : , Payload : [source : DotNetty.Transport
.Channels.Sockets.TcpServerSocketChannel] [message : Failed to create a new chan
nel from an accepted socket.] [exception : System.Net.Sockets.SocketException (0
x80004005): 远程主机强迫关闭了一个现有的连接。
   at DotNetty.Transport.Channels.Sockets.SocketChannelAsyncOperation.Validate()

   at DotNetty.Transport.Channels.Sockets.TcpServerSocketChannel.TcpServerSocket
ChannelUnsafe.FinishRead(SocketChannelAsyncOperation operation)] , EventName : W
arningInfo, Timestamp : 2016-07-24T11:30:56.8047198Z, ProcessId : 7452, ThreadId
 : 8832

EventId : 3, Level : Informational, Message : , Payload : [source : DotNetty.Han
dlers.Logging.LoggingHandler] [message : [id: 0x716ab942, [::ffff:0:0]:3333] EXC
EPTION: System.Net.Sockets.SocketException (0x80004005): 远程主机强迫关闭了一个
现有的连接。
   at DotNetty.Transport.Channels.Sockets.SocketChannelAsyncOperation.Validate()

   at DotNetty.Transport.Channels.Sockets.TcpServerSocketChannel.TcpServerSocket
ChannelUnsafe.FinishRead(SocketChannelAsyncOperation operation)] [info : System.
Net.Sockets.SocketException (0x80004005): 远程主机强迫关闭了一个现有的连接。
   at DotNetty.Transport.Channels.Sockets.SocketChannelAsyncOperation.Validate()

   at DotNetty.Transport.Channels.Sockets.TcpServerSocketChannel.TcpServerSocket
ChannelUnsafe.FinishRead(SocketChannelAsyncOperation operation)] , EventName : I
nfoInfo, Timestamp : 2016-07-24T11:30:56.9140955Z, ProcessId : 7452, ThreadId :
8832

EventId : 4, Level : Warning, Message : , Payload : [source : DotNetty.Transport
.Channels.DefaultChannelPipeline] [message : An ExceptionCaught() event was fire
d, and it reached at the tail of the pipeline. It usually means the last handler
 in the pipeline did not handle the exception.] [exception : System.Net.Sockets.
SocketException (0x80004005): 远程主机强迫关闭了一个现有的连接。
   at DotNetty.Transport.Channels.Sockets.SocketChannelAsyncOperation.Validate()

   at DotNetty.Transport.Channels.Sockets.TcpServerSocketChannel.TcpServerSocket
ChannelUnsafe.FinishRead(SocketChannelAsyncOperation operation)] , EventName : W
arningInfo, Timestamp : 2016-07-24T11:30:56.9140955Z, ProcessId : 7452, ThreadId
 : 8832

EventId : 3, Level : Informational, Message : , Payload : [source : DotNetty.Han
dlers.Logging.LoggingHandler] [message : [id: 0x716ab942, [::ffff:0:0]:3333] EXC
EPTION: System.ObjectDisposedException: Safe handle has been closed
   at System.Net.Sockets.Socket.AcceptAsync(SocketAsyncEventArgs e)
   at DotNetty.Transport.Channels.Sockets.TcpServerSocketChannel.ScheduleSocketR
ead()
   at DotNetty.Transport.Channels.Sockets.AbstractSocketChannel.DoBeginRead()
   at DotNetty.Transport.Channels.AbstractChannel.AbstractUnsafe.BeginRead()] [i
nfo : System.ObjectDisposedException: Safe handle has been closed
   at System.Net.Sockets.Socket.AcceptAsync(SocketAsyncEventArgs e)
   at DotNetty.Transport.Channels.Sockets.TcpServerSocketChannel.ScheduleSocketR
ead()
   at DotNetty.Transport.Channels.Sockets.AbstractSocketChannel.DoBeginRead()
   at DotNetty.Transport.Channels.AbstractChannel.AbstractUnsafe.BeginRead()] ,
EventName : InfoInfo, Timestamp : 2016-07-24T11:30:56.9453457Z, ProcessId : 7452
, ThreadId : 8832

EventId : 4, Level : Warning, Message : , Payload : [source : DotNetty.Transport
.Channels.DefaultChannelPipeline] [message : An ExceptionCaught() event was fire
d, and it reached at the tail of the pipeline. It usually means the last handler
 in the pipeline did not handle the exception.] [exception : System.ObjectDispos
edException: Safe handle has been closed
   at System.Net.Sockets.Socket.AcceptAsync(SocketAsyncEventArgs e)
   at DotNetty.Transport.Channels.Sockets.TcpServerSocketChannel.ScheduleSocketR
ead()
   at DotNetty.Transport.Channels.Sockets.AbstractSocketChannel.DoBeginRead()
   at DotNetty.Transport.Channels.AbstractChannel.AbstractUnsafe.BeginRead()] ,
EventName : WarningInfo, Timestamp : 2016-07-24T11:30:56.9453457Z, ProcessId : 7
452, ThreadId : 8832

EventId : 3, Level : Informational, Message : , Payload : [source : DotNetty.Han
dlers.Logging.LoggingHandler] [message : [id: 0x716ab942, [::ffff:0:0]:3333] UNR
EGISTERED] [info : ] , EventName : InfoInfo, Timestamp : 2016-07-24T11:30:56.945
3457Z, ProcessId : 7452, ThreadId : 8832

**Comment by nayato** [comment]
duplicate #133
