### ISSUE TITLE
DotNetty Server use HttpClient throw Timeout Exception

### ISSUE THREAD

**Issue by ArvinHsieh** [Azure/DotNetty#146]
I create a server to listen client request.
But...
When i used HttpClient in the ServerHandler > ChannelRead.
This will throw HttpTimeout Exception.

sample source: 
https://drive.google.com/open?id=0B40daTESrAXwSVBqV3JhZTc1Q3c

**Comment by nayato** [comment]
It is likely you're blocking in event loop which is highly recommended to avoid.
