### ISSUE TITLE
Netty api corresponding version ?

### ISSUE THREAD

**Issue by tebeco** [Azure/DotNetty#147]
On Netty repository I can see two branch 0.4.x and 0.5.x
The top level api (static class member that look like a factory) has been changed
I'm wondering if this version is intended to look like one or another or if it's an adaptation to c# which a different set of factory api ?

**Comment by nayato** [comment]
we try to follow the latest (4.1.x). There are few differences in ChannelHandler interface as it includes methods from both InboundChannelHandler and OutboundChannelHandler. It is derivative from the fact that I started with porting 5.0 that was then canceled. Still I find this model more flexible and it is easy to adapt the other code to that model while porting other parts.

**Comment by tebeco** [comment]
Thx for the answer
