### ISSUE TITLE
Why AcceptOutboundMessage is not abstract？

### ISSUE THREAD

**Issue by zmyer** [Azure/DotNetty#148]
In DotNetty，the function `public bool AcceptOutboundMessage(object msg) => msg is T;` is not abstract，so that much more limitions when using EmbeddedChannel.

**Comment by nayato** [comment]
I believe you mean not `virtual`. That makes sense. It is generally a problem during port as the default in Java is virtual while in .NET it isn't.

**Comment by nayato** [comment]
Fixed in 0.4.0
