### ISSUE TITLE
exception in TcpSocketServerChannel

### ISSUE THREAD

**Issue by lobster2012-user** [Azure/DotNetty#153]
DotNetty\src\DotNetty.Transport\Channels\Sockets\TcpServerSocketChannel.cs

`
while (allocHandle.ContinueReading())
                        {
                            connectedSocket = null;
                            connectedSocket = ch.Socket.Accept();//invalid operation on non blocking socket
                            message = new TcpSocketChannel(ch, connectedSocket, true);
                            ch.ReadPending = false;
                            pipeline.FireChannelRead(message);

```
                        allocHandle.IncMessagesRead(1);
                    }
```

`

I have the same error in helios.
I'm not sure that is critical error.
Youcan see in Echo.Server example+ browser

**Comment by yyjdelete** [comment]
It may be noise when FirstChanceException is used or debug.
An workaround is using the below channel instead of directly using TcpServerSocketChannel in bootstarp.
```C#
    public class MyTcpServerChannel : TcpServerSocketChannel
    {
        private static readonly ChannelMetadata METADATA = new ChannelMetadata(false);

        public override ChannelMetadata Metadata => METADATA;
    }
```
