### ISSUE TITLE
 Implementation of DirectBuffer

### ISSUE THREAD

**Issue by zsybupt** [Azure/DotNetty#167]
Hi all, currently dotnetty has heap buffer,  Is there any purpose to implement direct buffer, thanks

**Comment by nayato** [comment]
I don't see a point at the moment. In Java there are specific reasons for that:
- to avoid buffers to appear in heap and mess up GC
- to avoid extra copy on NIO interactions
.NET uses different technique for interop (pinning) + pooled buffer allocator works with big arrays that naturally land in LOH and hence not affecting GC.

**Comment by zsybupt** [comment]
Thanks for your answer, I will close this.
