### ISSUE TITLE
How to get ping message in client?

### ISSUE THREAD

**Issue by tonn2y** [Azure/DotNetty#169]
How to get ping message in client?

**Comment by nayato** [comment]
@tonn2y that is very vague question. Generally, it is a higher level concern. Here's what Azure IoT does for MQTT in client: https://github.com/Azure/azure-iot-sdks/blob/master/csharp/device/Microsoft.Azure.Devices.Client/Transport/Mqtt/MqttIotHubAdapter.cs#L244

**Comment by tonn2y** [comment]
Thanks! I will try.
