### ISSUE TITLE
who used in a production environment yet?

### ISSUE THREAD

**Issue by 472405746** [Azure/DotNetty#176]

**Comment by tomek14** [comment]
I'm using it in production enviroment, as a server for gps trackers. Works great!. Rigth now i'm using  version 0.32 from nuget, but I'm working on next version of my gps tracker server based on DotNetty with binaries compiled form dev branch, beacause it has better Loging abstraction (Microsoft.Extensions.Logging)

**Comment by nayato** [comment]
@472405746, we use it in Azure IoT. E.g.: https://github.com/Azure/azure-iot-sdk-csharp/blob/master/device/Microsoft.Azure.Devices.Client/Transport/Mqtt/MqttTransportHandler.cs#L490
@tomek14, I'm working on 0.4.0 release right now.

**Comment by StormHub** [comment]
I have been using both DotNetty and original Java Netty in production environment for quite some time.
