### ISSUE TITLE
Could DotNetty support  for Unity3d?

### ISSUE THREAD

**Issue by idzzly** [Azure/DotNetty#179]
DotNetty use some syntax and  features after .net 2.0 (eg: Lambda, $ and  System.Threading.Tasks).
But Unity3d only supports .net 2.0.
Could DotNetty support  for Unity3d?

**Comment by qcjxberin** [comment]
应该不行吧，现在都已经支持.net core了，.net core支持的特性.net 2.0应该不支持吧。

**Comment by nayato** [comment]
@idzzly it's a stretch to even support .net 4.5.1 as it is past EOL already. It is up to Unity to support new version of .NET. AFAIK they had plans to move to .NET 4.6.

**Comment by wavebit** [comment]
I have tested. DotNetty does not work with Unity 2017.1 (.net 4.6). ;(
