### ISSUE TITLE
How to create simple tcp server in DotNetty in c#

### ISSUE THREAD

**Issue by mnbgh** [Azure/DotNetty#184]
How to create simple tcp server in DotNetty in c#

**Comment by nayato** [comment]
https://github.com/Azure/DotNetty/blob/dev/examples/Echo.Server/ should give an idea. A couple of extra things it does on top of just TCP is framing (LengthFieldPrepender+LengthFieldBasedFrameDecoder) and TLS (TlsHandler). I'd suggest playing with Echo server and client to get started, maybe put extra LoggingHandlers in between channel handlers in pipeline to see what they do.

**Comment by mzelecom** [comment]
i cant used echo.server for simple tcp server.
please upload a simple code to use.
i just need these event.
client connected.
client disconnected.
Receive data from client.

thank you

**Comment by Tochemey** [comment]
You can this out https://github.com/Tochemey/ModFreeSwitch/tree/master/ModFreeSwitch/Handlers/inbound.

I was able to write a Tcp Server using the DotNetty.

**Comment by mzelecom** [comment]
hi Tochemey
please write a tcp server using DotNetty.
i need it.
thanks

**Comment by ColinM9991** [comment]
@mzelecom Study and read documentation, don't demand people do your code for you because you "need it"
