### ISSUE TITLE
MessageToByteEncoder is not usable.

### ISSUE THREAD

**Issue by jordanabrahambaws** [Azure/DotNetty#190]
You are unable to inherit the class MessageToByteEncoder.

**Comment by nayato** [comment]
Can you elaborate? Looks fine to me: https://github.com/Azure/DotNetty/blob/6d1a58df8eeea4580b469ee9a221bd10c540531a/src/DotNetty.Codecs/MessageToByteEncoder.cs#L13

**Comment by jordanabrahambaws** [comment]
http://prntscr.com/e3tsny

The other codecs show up except for MessageToByteEncoder. I'm not using it anywhere else in the project.

**Comment by jordanabrahambaws** [comment]
Inside of the codecs assembly XML file, there is no member found for MessageToByteEncoder as well. I swear I haven't touched it.

**Comment by nayato** [comment]
I suppose you're using nuget. It isn't there in 0.3.2. It is in 0.4.x. pls try https://www.nuget.org/packages/DotNetty.Codecs/0.4.0

**Comment by jordanabrahambaws** [comment]
You would be correct. I was using the older version. Thank you!
