### ISSUE TITLE
Does dotNetty run in .NET 4.6?

### ISSUE THREAD

**Issue by mmartell** [Azure/DotNetty#193]
After cloning the repo, when I opened the DotNetty.sln file in Visual Studio 2015 Update 3 the individual projects failed to load becuase I did not have .NET Core installed. Is .NET Core a runtime requirement of dotNetty? I was hoping to use it in a .NET 4.6 environment.

Thanks,
Mike

**Comment by nayato** [comment]
you can use DotNetty as a nuget on both .NET Core and .NET Framework (4.5.1 and up). Opening solution now requires VS 2017 RC and dotnet rc4 tooling.
