### ISSUE TITLE
Dotnetty vs alternatives

### ISSUE THREAD

**Issue by debdattabasu** [Azure/DotNetty#199]
Hi. 
First of all, thank you for your awesome work. I am trying to understand the .NET landscape, and evaluating DotNetty vs the native networking stack. The standard library has TCPListener which  is easy to use, works great with async/await, etc. The kestrel folks call libuv directly. 

Why, is there a need for DotNetty, or to call libuv when the standard library provides functionality that is simple and easy to use. 

Thanks.

**Comment by Maximusya** [comment]
If you can easily build error-free, easy to understand/debug - and scalable! - system around TcpListener (TcpClient) then by all means you don't need any networking library.
It's just that Socket/TcpClient API do not impose any obvious architecture - thus internet is flooded with naive, incomplete and incorrect samples that often don't do more than echo or ping-pong. In rare cases libraries/articles touch the surface of session management, authentication, resource consumption etc. Every programmer must try to write one's own networking library ;)

Libuv (if I read it right) just offers a low-level event-based cross platform API - still not imposing any architecture.

[Dot]Netty offers a well-tested, production-ready model for building extendable, scalable networking services. It may look "enterprise" at first (hell, it still looks too much "enterprise" for me), but sooner or later you would come to similar solutions - if you happen to grow your own library.

Still DotNetty is v0.4.0 now: if you decide to use it you may encounter edge-cases not covered yet. Somewhere here it was stated that it is used for Azure IoT backend services.

**Comment by debdattabasu** [comment]
Hi.
Thank you for your quick response. I do understand that libraries are often needed to fill in higher level functionality, but my question is different. 

The issue is that DotNetty is based on Netty 4, which fundamentally different way to do async sockets than that in the standard library. The standard library works with tasks and async/await, which distributes work across a work stealing thread pool. DotNetty on the other hand pins a connection to a particular Thead. 

These are both perfectly fine in and of themselves, but confused about what is the idiomatic way to do this in C#.  The standard library with async/await, looks a lot like go, which I like. However, major projects from Microsoft seem to do other things, like DotNetty which relies on SocketAsyncEventArgs to build an event loop abstraction, and kestrel, which bypasses the .net stack altogether and calls libuv. 

My question is, is there a technical reason not to use the standard library that I am missing?

Regards.

**Comment by AwsomeCode** [comment]
I also had same question in my mind. I also like answer for this.

**Comment by nayato** [comment]
@debdattabasu ideally we should be using libuv underneath as well. Unfortunately, we're not there yet and it is likely that either we'll gain libuv (or RIO)-based channels through [System.IO.Pipelines](https://github.com/dotnet/corefxlab/tree/master/src/System.IO.Pipelines) or it will take over many concepts behind DotNetty's core to a point where it becomes redundant.
Kestrel is about HTTP/S only IIRC. DotNetty (as Netty) is about making writing efficient networking stack easy. Async/await at that level while may be good for making intent clear chips away on the performance side of things. DotNetty is about providing higher-level framework for writing networking stacks outside of staple HTTP+JSON that you get OOTB in .NET.

**Comment by debdattabasu** [comment]
@nayato The event loop model seems to me to be a regression, usability wise, from the task based model in the standard library. The task model with async/await seems even better than the fiber model in go, because you can write straightforward synchronous-looking code using await when required and also use task combinators when required. A high level networking framework could be implemented using the task based model as well. 

From what I understand, the reason for DotNetty is that an event loop may be better for performance than a work stealing pool, but I am wondering why. 

Interestingly, Netty 5 wanted to ditch the connection pinning event loop and put socket polling jobs as tasks onto a ForkJoinPool, which is basically a work stealing thread pool similar to the one in c#. The project got dropped for unrelated reasons, however. You can find more about it here: http://netty.io/wiki/new-and-noteworthy-in-5.0.html under "Even more flexible threading model". 

That change would have made Netty 5 conceptually equivalent to the task based model in C#.  I haven't run specific benchmarks, so want to get your opinion on what will be the performance impact of building low level protocols using tasks and async/await vs dotnetty, and why.

**Comment by nayato** [comment]
@debdattabasu I'm well aware what netty 5.0 was about in terms of concurrency. It was not the same as with .NET's IOCP thread pool. It was a form of abstracting away event loop from underlying thread factory. It was still taking thread and working on it as an event loop worker thread, just releasing it back to pool when work piled up in worker's queue was exhausted. BTW, netty 5.0 was canceled due to lack of visible improvement over the set of breaking changes it implied.
Next, async/await has nothing to do with threading model. Kestrel is live example of that. They're working on event loop up to a moment of dispatching an HTTP request to user which they didn't want to tell people what to do and what not to do (e.g. blocking thread) so they send it to thread pool as a work item. IO.Pipelines takes the same approach: it does not control threading in any way and with libuv underneath you stay on event loop after awaiting on ReadAsync. When you think about Proxy or Gateway scenarios you very much want to stay on event loop up to a point of dispatching a request to the next party. These scenarios are covered in IO.Pipelines and DotNetty (to some extent).
Further more, in DotNetty I've made sure to ease user's life by implementing TaskScheduler that dispatches work to event loop allowing continuations to return control to event loop. As a result you can use thread local resources effeciently and skip on synchronization costs for much of the work.

**Comment by debdattabasu** [comment]
@nayato 
Thanks for the explanation. If I understand correctly, the event loop model is the way to go for protocol level performance, which will matter more in cases with tight loops such as proxies. Tasks can still be created/awaited from the channel handlers for doing higher level scheduling, and everything will interoperate seamlessly. That's awesome. 

I have some code that currently decodes protobuf data using NetworkStream::ReadAsync with async/await. Will revisit the code if performance becomes an issue. 

Thanks for your time. 
Regards.

**Comment by StormHub** [comment]
@debdattabasu Dot/Netty both aiming for having a 'high level' abstraction over 'network details' without performance penalties as oppsite to 'hand crafted' pipeline processing. If something pops up in handlers as a business objects whereas underlying protocol might be http over JSON or protobuf, it does not even matter that much. In a low latency IoT world today, that is a *big* advantage. Further more, the buffer management/allocations in Dot/Netty are very efficient to allow you to get away with 'raw byte' copying when dealing with low level protocols.

**Comment by endink** [comment]
great! great! if u used netty before now, u will like this project , Socket api is hard to use, and netty make it easy
