### ISSUE TITLE
Should I Wait for DotNetty 1.0?

### ISSUE THREAD

**Issue by mmartell** [Azure/DotNetty#200]
From the examples and the 400 included unit tests, this project looks quite production ready. Others have suggested that since it is only at version 0.4, there may features and edge cases that aren't supported yet.

Please summarize the main features that are not in the current release, and perhaps also an estimated time frame for a 1.0 release.

**Comment by nayato** [comment]
The main reason DotNetty is not 1.0 is us not willing to commit to non-breaking mode. We are more or less conservative about API surface area but if things will need significant reshuffling we wouldn't want to have a hard stop at not breaking old API.
