### ISSUE TITLE
how to open it?please!please!please!

### ISSUE THREAD

**Issue by chucongwen1** [Azure/DotNetty#201]
i use vs2015 but  that the project  cannot load,please help me

**Comment by nayato** [comment]
We've migrated to vs 2017. That only matters if you want to contribute to dotnetty itself. If you'd like to use it, you can reference it as a nuget dependency in project in VS 2015.

**Comment by chucongwen1** [comment]
i use vs2012 import dll  is ok?

**Comment by nayato** [comment]
Nuget packages v0.4.2 feature .NET 4.5.1 and .NET Standard 1.3 libraries. VS 2012 works with .NET 4.5. Move to support .NET 4.5 is in dev branch now but 0.4.3 will not be released for at least another week. If you need it now, you can build it once with VS 2017 RC and use them until 0.4.3 comes around.
