### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by slugnani** [Azure/DotNetty#203]
If using .NET framework version > 4.5.1, all .NET framework 4.5.1 packages used by Dotnetty must be installed, look at the screenshot.
![screen shot 2017-02-28 at 10 12 33](https://cloud.githubusercontent.com/assets/3220273/23398881/7d26ff50-fd9e-11e6-8873-5284ff043f46.png)

 Is this the best solution? Can you change this dependency from NETFramework = 4.5.1 to NETFramework >= 4.5.1 ?

**Comment by nayato** [comment]
I believe dependencies now are pulled through because of how they're setup in Microsoft.Extensions.Logging package. It pulls in standard library which in turn pulls all these packages.
