### ISSUE TITLE
SwappedByteBuffer.WriteUnsignedShort(ushort) throws NotImplementedException

### ISSUE THREAD

**Issue by andreasdamm** [Azure/DotNetty#207]
When calling the DotNetty.Buffers.IByteBuffer.WriteUnsignedShort(ushort) implementation of DotNetty.Buffers.SwappedByteBuffer a NotImplementedException is thrown.

**Comment by StormHub** [comment]
https://github.com/Azure/DotNetty/blob/dev/src/DotNetty.Buffers/SwappedByteBuffer.cs#L247
looks like a bug to me
