### ISSUE TITLE
telnet Server example deadlock question

### ISSUE THREAD

**Issue by uliian** [Azure/DotNetty#228]
in class TelnetServerHandler
```
        public override void ChannelActive(IChannelHandlerContext contex)
        {
            contex.WriteAsync(string.Format("Welcome to {0} !\r\n", Dns.GetHostName()));
            contex.WriteAsync(string.Format("It is {0} now !\r\n", DateTime.Now));
            contex.Flush();
        }
```
change to 
```
        public override async void ChannelActive(IChannelHandlerContext contex)
        {
            await contex.WriteAsync(string.Format("Welcome to {0} !\r\n", Dns.GetHostName()));
            await contex.WriteAsync(string.Format("It is {0} now !\r\n", DateTime.Now));
            contex.Flush();
        }
```

When Telnet connecting to the Server, blocking similar deadlocks will happen; but when client enter enter telnet it is back to normal.

**Comment by nayato** [comment]
WriteAsync simply posts message for sending. Actual sending through network is initiated with Flush. Basically you're awaiting a thing that is not meant to complete ever. Proper way to await would be to save tasks in variables and await on them after Flush is called.

**Comment by uliian** [comment]
If so, why is the write method designed to be awaitable? It is easy to give a hint: call the method when the io operation, if you do not wait to complete the next write operation will make people wonder if the first write operation will conflict. It is more intuitive to design flush as a way to wait

**Comment by nayato** [comment]
Because that's what you want feedback for on individual message basis. You may flush separately from writing based on time or some batching strategy in a different handler closer to pipeline head. I would say having a better xml doc on WriteAsync would be the best solution here.

**Comment by uliian** [comment]
thanks
