### ISSUE TITLE
How to create Synchronous receive message in DotNetty in c#

### ISSUE THREAD

**Issue by hsdotnet** [Azure/DotNetty#233]

**Comment by nayato** [comment]
more context pls. If you want to write synchronous code while working with dotnetty, it's not suited for that without establishing producer-consumer (dotnetty channel - producer, client code - consumer). DataFlow, Rx and even just ConcurrentQueue/BlockingCollection-based setup might help with that.
If it's about synchronous communication (e.g. request-response), then there are no primitives in DotNetty for that but it's trivial to build.
