### ISSUE TITLE
The principle of work of asynchronous requests in DotNetty is not understandable.

### ISSUE THREAD

**Issue by ArchiEcho** [Azure/DotNetty#240]
Take, for example, the usual TCP port scanner.

**The main task start code:**

    private async Task CheckServers(int concurrencyLevel, int port, int timeout)
            {
                var group = new MultithreadEventLoopGroup();
    
                var tasks = new Task[concurrencyLevel];
                for (int i = 0; i < tasks.Length; i++)
                    tasks[i] = CheckIP(port, timeout, group);
                            
                await Task.WhenAll(tasks);
                await group.ShutdownGracefullyAsync();
            }

    private async Task CheckIP(int port, int timeout, MultithreadEventLoopGroup group)
            {
                foreach (var ip in ipCollection.GetConsumingEnumerable()) // A collection that provides IP addresses
                {
                    if (await PortScanner.IsOpenPortAsync(ip, port, timeout, group))
                        Logging.Add(ip + ":" + port.ToString());
                }
            }

**And the class itself, which checks the port using DotNetty transport:** 

    internal class PortScanner
        {
            internal static async Task<bool> IsOpenPortAsync(string ip, int port, int timeout, MultithreadEventLoopGroup _group)
            {
                var result = false;
    
                try
                {
                    var bootstrap = new Bootstrap();
                    bootstrap
                        .Group(_group)
                        .Channel<TcpSocketChannel>()
                        .Option(ChannelOption.TcpNodelay, true)
                        .Option(ChannelOption.ConnectTimeout, TimeSpan.FromMilliseconds(timeout))
                        .Handler(new ActionChannelInitializer<ISocketChannel>(channel =>
                        {
                            IChannelPipeline pipeline = channel.Pipeline;
                            pipeline.AddLast("framing-enc", new LengthFieldPrepender(2));
                            pipeline.AddLast("framing-dec", new LengthFieldBasedFrameDecoder(ushort.MaxValue, 0, 2, 0, 2));
                            pipeline.AddLast("echo", new EchoClientHandler());
                        }));
    
                    IChannel clientChannel = await bootstrap.ConnectAsync(IPAddress.Parse(ip), port);
                    result = clientChannel.Active;
                    await clientChannel.CloseAsync();
                }
                catch
                {
                    result = false;
                }
    
                return result;
            }
    }

And the handler, in accordance with the requirements of DotNetty:

    internal class EchoClientHandler : ChannelHandlerAdapter
        {
            public EchoClientHandler()
            {
            }
    
            public override void ChannelActive(IChannelHandlerContext context)
            {
            }
    
            public override void ExceptionCaught(IChannelHandlerContext context, Exception exception)
            {
                context.CloseAsync();
            }
        }

**Question:** for some reason (my mistake \ architectural error \ bug of the library itself) - the scanner does not work as it should, the queries work out immediately (it seems that instead of waiting for the connection to end from `await bootstrap.ConnectAsync` - the method does not wait for the connection to the IP address to end , But immediately goes to `await clientChannel.CloseAsync`). What is the reason for this behavior?

**Comment by wind-rider** [comment]
Большинство людей не может вам помочь если вопрос на русском.. Пожалуйста, переводите его на английском.

**Comment by nayato** [comment]
maybe try checking what causes CloseAsync to be called in the first place. E.g. exception provided in exceptioncaught, also error returned from ConnectAsync
