### ISSUE TITLE
MQTT UWP Example

### ISSUE THREAD

**Issue by ckrath** [Azure/DotNetty#248]
Please provide example code snippet using DotNetty.Codecs.Mqtt on Windows IoT.

**Comment by nayato** [comment]
You may find this commit useful:
https://github.com/Azure/azure-iot-sdk-csharp/commit/93444391ba734cb57ad23a134d7125c2ee605fd8#diff-0856ee23a0f0310003139ca1f64bc0a8
this SDK uses dotnetty for MQTT and that commit specifically adds support for UWP.

**Comment by nayato** [comment]
We have no plans to do an extensive examples to be honest.
