### ISSUE TITLE
ReadTimeoutHandler doesn’t work if timeout occurs in the middle of WriteAndFlushAsync 

### ISSUE THREAD

**Issue by rhssiiy** [Azure/DotNetty#255]
Take a look at this example:

```csharp
public class EchoServerHandler : ChannelHandlerAdapter
    {
        byte[] array;
        IChannelHandlerContext context;

        public override void ChannelActive(IChannelHandlerContext context)
        {
            this.array = new byte[100000];
            this.context = context;
            this.GenerateTraffic();
        }

        public override void ExceptionCaught(IChannelHandlerContext context, Exception exception)
        {
            Console.WriteLine(exception);
            context.CloseAsync();
        }

        async void GenerateTraffic()
        {
            try
            {
                IByteBuffer buffer = Unpooled.WrappedBuffer(this.array);
                // Flush the outbound buffer to the socket.
                // Once flushed, generate the same amount of traffic again.
                await this.context.WriteAndFlushAsync(buffer);

                // Comment this to make ReadTimeoutHandler great again
                this.GenerateTraffic();
            }
            catch
            {
                await this.context.CloseAsync();
            }
        }
    }

    class MainClass
    {
        static async Task RunClientAsync()
        {
            var bossGroup = new MultithreadEventLoopGroup(1);
            var workerGroup = new MultithreadEventLoopGroup();

            try
            {
                var bootstrap = new ServerBootstrap();
                bootstrap
                    .Group(bossGroup, workerGroup)
                    .Channel<TcpServerSocketChannel>()
                    .Option(ChannelOption.SoBacklog, 100)
                    .Option(ChannelOption.TcpNodelay, true)
                    .ChildHandler(new ActionChannelInitializer<ISocketChannel>(channel =>
                    {
                        IChannelPipeline pipeline = channel.Pipeline;
                        pipeline.AddLast(new ReadTimeoutHandler(60));
                        pipeline.AddLast("echo", new EchoServerHandler());
                    }));

                IChannel boundChannel = await bootstrap.BindAsync(new IPEndPoint(IPAddress.Parse("0.0.0.0"), 1111));

                Console.ReadLine();

                await boundChannel.CloseAsync();
            }
            finally
            {
                await Task.WhenAll(
                    bossGroup.ShutdownGracefullyAsync(TimeSpan.FromMilliseconds(100), TimeSpan.FromSeconds(1)),
                workerGroup.ShutdownGracefullyAsync(TimeSpan.FromMilliseconds(100), TimeSpan.FromSeconds(1))
                );
            }
        }

        public static void Main(string[] args)
        {
            RunClientAsync().Wait();
        }
    }
```

Server constantly sends a lots of data, client connects and doesn’t read or write anything. At some point  `WriteAndFlushAsync` blocks because of overflow network stack buffer. After that reading timeout never occurs and session lives forever. Moreover, `CloseAsync` doesn’s work after that too.

I’ve used `nc --send-only 127.0.0.1 1111` as a client. Tested on Linux and Windows, on mono 5.0.0.100.

**Comment by StormHub** [comment]
This is not actually the problem of ReadTimeoutHandler. In the server handler, the async method GenerateTraffic actually causing netty event loop to sort of spinning forever. This would work if you just want to keep pushing for data

void GenerateTraffic()
        {
            IByteBuffer buffer = Unpooled.WrappedBuffer(this.array);

            // Flush the outbound buffer to the socket.
            // Once flushed, generate the same amount of traffic again.
            this.ctx.WriteAndFlushAsync(buffer)
                .ContinueWith(_ => this.GenerateTraffic());
        }

**Comment by rhssiiy** [comment]
Thanks for the answer.

I've made like this:

```csharp
        async void GenerateTraffic()
        {
            try
            {
                IByteBuffer buffer = Unpooled.WrappedBuffer(this.array);
                // Flush the outbound buffer to the socket.
                // Once flushed, generate the same amount of traffic again.
                if (this.context.Channel.Open)
                    this.context.WriteAndFlushAsync(buffer)
                        .ContinueWith(_ => this.GenerateTraffic());
            }
            catch (Exception e)
            {
                await this.context.CloseAsync();
            }
        }
```

It hasn't helped, reading timeout still doesn't occur.

I've tried to run this example (both versions) on .net core 1.1 - it works like a charm.
The problem seems to be related to mono but I'm not sure.

**Comment by wuzhenda** [comment]
I got the same problem at `version="0.4.7" targetFramework="net46"`  ;After setting the ReadTimeoutHandler, like this
` .ChildHandler(new ActionChannelInitializer<ISocketChannel>(channel =>
                {
                    IChannelPipeline pipeline = channel.Pipeline;
                    pipeline.AddLast("Frame-enc", new Encode());
                    pipeline.AddLast("Frame-dec", new Decode());

                    pipeline.AddLast("idleStateHandler", new ReadTimeoutHandler(60));
                    pipeline.AddLast("nettyHandler", new NettyHandler());
                }));`

when I use  ` ctx.Channel.WriteAndFlushAsync(message).TimeoutAfter(TimeSpan.FromMinutes(2)); `  ,
And timeout happened in the task. after that the channel indeed is dead,but the ReadTimeout not be catched.
