### ISSUE TITLE
Is not  the IByteBuffer.ReadUnsignedShort  support Orderbyte autoed?

### ISSUE THREAD

**Issue by cswares** [Azure/DotNetty#257]
I use the LittleEndian stream send.
the SelfDecode.Decode function which readed package length (use readunsignedshort) is error length(BigEndian)

**Comment by yyjdelete** [comment]
The default order of `IByteBuffer` is `BE` as netty( in Java) does. You need to call `buf.WithOrder(ByteOrder.LittleEndian)` to get an LE buffer at the receiving end. It works like an wapper of byte array, and order of IByteBuffer won't be transported to another side. And there is no way to 
auto detect whether a field is BE/LE without protocol. 

---

`IByteBuffer`的默认大小端是BE, 因为这也是Java版netty的默认值. 如果你需要的话可以在接收端调用`buf.WithOrder(ByteOrder.LittleEndian)`来返回一个LE的封装`IByteBuffer`(不会改变原始buf的大小端).

IByteBuffer更接近于传输所使用的东西, 相当于byte数组的一个封装, 其大小端信息并不会通过网络传输(也无法传输, 因为可以一部分用大端写入, 另一部分用小端写入), 因此在接收端不会保留原始的大小端信息.

大小端的选择一般都在协议层面实现, 一般协议都选择固定的大小端, 所以也没必要去识别.另外没有什么办法在不知道协议的情况下智能识别协议中的一个字段是大端还是小端, 因为一般情况下按大小端都能读出正常(不一定正确)的数据.  除非自己定义了特殊的协议结构, 比如UTF8的BOM, 或者例如在协议中固定写一个0x55AA的MAGIC, 然后观察第一字节是55h还是AAh.

看不到你写的`SelfDecode.Decode`, 英文也不是看的很明白, 所以各方面都说了一点, 希望能有帮助.

**Comment by cswares** [comment]
能在客户端或服务端的启动代码里配置字节序吗？

**Comment by yyjdelete** [comment]
Seems no global settings.  You can just use `WithOrder` to get an LE buf before read, or add an `BE2LEDecoder` to your pipeline before read(not tested).

```C#
public class BE2LEDecoder : MessageToMessageDecoder<IByteBuffer>
{
    protected override void Decode(IChannelHandlerContext context, IByteBuffer message, List<object> output)
    {
        output.Add(message.WithOrder(ByteOrder.LittleEndian).Retain());
    }
}
```
---

好像没有全局的. 但你可以在你读之前用`var bufLE = buf.WithOrder(ByteOrder.LittleEndian)`来获取一个LE的, 之后一直用这个新bufLE. 或者在pipeline中读取的那级之前插入一个`BE2LEDecoder`(未测试).

**Comment by cswares** [comment]
ok，thank you very much.

**Comment by fyee311** [comment]
Can't find the method WithOrder
