### ISSUE TITLE
channel attributes ReadOnly

### ISSUE THREAD

**Issue by ukluk** [Azure/DotNetty#258]
Is it possible to use Attributes as a property bag to store metadata related to each session?
The only exposed methods are HasAttributes and GetAttribute. It is missing a public "SetAttribute"

The use case is:
After Authentication, find some decorator information from the database (I/O) and reuse it for each received message in the entire session per channel.

**Comment by nayato** [comment]
it is settable: call GetAttribute(..), then call Set on returned attribute object:
https://github.com/Azure/DotNetty/blob/dev/src/DotNetty.Common/Utilities/IAttribute.cs#L23
