### ISSUE TITLE
Any recent benchmarks?

### ISSUE THREAD

**Issue by pranavmehta** [Azure/DotNetty#269]
I've seen the benchmarks published on the dotnetty project about a year ago with regards to the Azure IoT protocol gateway. 

Just wondering if there have been any recent benchmarks? Just curious. Not looking for a specific use case.

**Comment by nayato** [comment]
Here's my recent test with MQTT server (dumb PUBACK for every incoming PUBLISH) on D3v2 VM
TLS | Payload size | Concurrency | Throughput, 1000 req/sec | Avg latency, ms | CPU, %
-- | -- | -- | -- | -- | --
  | min | 256 | 117 | 2.3 | 75
  | min | 950 | 103 | 9.2 | 68
yes | min | 256 | 74 | 3.5 | 97
  | 1KB | 256 | 100 | 2.6 | 79
  | 1KB | 950 | 79 | 12.0 | 74
yes | 1KB | 256 | 55 | 4.7 | 96
yes | 4KB | 256 | 43 | 5.9 | 88
yes | 16KB | 256 | 14 | 18.7 | 72

**Comment by nayato** [comment]
still need to re-run with libuv transport and try it also on linux.
