### ISSUE TITLE
Cloud I use dotnetty with protobuf-net ?

### ISSUE THREAD

**Issue by PMExtra** [Azure/DotNetty#274]
I know there is a library called `DotNetty.Codecs.Protobuf` that using `Google.Protobuf` for serialization.

But I have another library called [**protobuf-net**](https://github.com/mgravell/protobuf-net), that follows typical .NET patterns and more convenient. I have a legacy project using **protobuf-net** and now want to migrate to dotnetty.

Could I still use protobuf-net instead of Google's library?

**Comment by nayato** [comment]
you could sure do that assuming you build your own codec. We have no plans supporting protobuf-net at the time but I assume it should be straight-forward to write a codec like one we have for google's version.
