### ISSUE TITLE
SingleThreadEventExecutor crash with ArgumentOutOfRangeException in PollTask() with DotNetty0.4.5

### ISSUE THREAD

**Issue by yyjdelete** [Azure/DotNetty#275]
I found the strange crash with DotNetty 0.4.5 after run service for about 3days, and it make all EventLoops stops.

But ManualResetEventSlim only throw ArgumentOutOfRangeException when `timeout` is less than -1 ms or more than int.MaxValue ms(about 24day20hour31min23sec). But the onlything use `Schedule` in my service is an `IdleStateHandler(150s, 50s, 0)` and an auto reconnect task with `1/5/10/20/30/60mins`.

I Will make an debug build try to see what happen later.

@nayato Any idea for what happen there?

<Details>

```
FirstChanceException: System.ArgumentOutOfRangeException: 指定的参数已超出有效值的范围。
参数名: timeout
   在 System.Threading.ManualResetEventSlim.Wait(TimeSpan timeout)
   在 DotNetty.Common.Concurrency.SingleThreadEventExecutor.PollTask()
   在 DotNetty.Common.Concurrency.SingleThreadEventExecutor.RunAllTasks(PreciseTimeSpan timeout)
   在 DotNetty.Common.Concurrency.SingleThreadEventExecutor.<Loop>b__25_0()

SingleThreadEventExecutor worker: execution loop failed System.ArgumentOutOfRangeException: 指定的参数已超出有效值的范围。
参数名: timeout
   在 System.Threading.ManualResetEventSlim.Wait(TimeSpan timeout)
   在 DotNetty.Common.Concurrency.SingleThreadEventExecutor.PollTask()
   在 DotNetty.Common.Concurrency.SingleThreadEventExecutor.RunAllTasks(PreciseTimeSpan timeout)
   在 DotNetty.Common.Concurrency.SingleThreadEventExecutor.<Loop>b__25_0()
```

</Details>

**Comment by nayato** [comment]
I can mitigate the issue by hard-capping max wait time (there's already a check that ticks are > 0) but I have no idea where scheduled item for 24+ days would come from.
