### ISSUE TITLE
ChannelOutboundBuffer Remove0 SafeSetFailure twice?

### ISSUE THREAD

**Issue by caozhiyuan** [Azure/DotNetty#276]
/// <summary>
        ///     Will remove the current message, mark its {@link ChannelPromise} as failure using the given {@link Exception}
        ///     and return {@code true}. If no   flushed message exists at the time this method is called it will return
        ///     {@code false} to signal that no more messages are ready to be handled.
        /// </summary>
        public bool Remove(Exception cause) => this.Remove0(cause, true);

        bool Remove0(Exception cause, bool notifyWritability)
        {
            Entry e = this.flushedEntry;
            if (e == null)
            {
                this.ClearNioBuffers();
                return false;
            }
            object msg = e.Message;

            TaskCompletionSource promise = e.Promise;
            int size = e.PendingSize;

            this.RemoveEntry(e);

            if (!e.Cancelled)
            {
                // only release message, fail and decrement if it was not canceled before.
                ReferenceCountUtil.SafeRelease(msg);

                Util.SafeSetFailure(promise, cause, Logger);
                if (promise != TaskCompletionSource.Void && !promise.TrySetException(cause))
                {
                    Logger.Warn($"Failed to mark a promise as failure because it's done already: {promise}", cause);
                }
                this.DecrementPendingOutboundBytes(size, false, notifyWritability);
            }

            // recycle the entry
            e.Recycle();

            return true;
        }

**Comment by caozhiyuan** [comment]
Util.SafeSetFailure(promise, cause, Logger);
            if (promise != TaskCompletionSource.Void && !promise.TrySetException(cause))
            {
                Logger.Warn($"Failed to mark a promise as failure because it's done already: {promise}", cause);
            }

**Comment by nayato** [comment]
@caozhiyuan do you have any more data as to when that happens?

**Comment by caozhiyuan** [comment]
@nayato in method Util.SafeSetFailure(promise, cause, Logger);  Set promise Exception one time  and in code blow (if (promise != TaskCompletionSource.Void && !promise.TrySetException(cause))) Set promise Exception twice will failure

**Comment by caozhiyuan** [comment]
@nayato when transport send data (AbstractSocketMessageChannel DoWrite ) error will raise this .

**Comment by caozhiyuan** [comment]
@nayato please take a look

**Comment by caozhiyuan** [comment]
@nayato  there real has a problem.
https://github.com/Azure/DotNetty/blob/dev/src/DotNetty.Transport/Channels/ChannelOutboundBuffer.cs#L238-L242
