### ISSUE TITLE
Is it possible to deploy a server made with DotNetty as PAAS on azure ? 

### ISSUE THREAD

**Issue by Djangoum** [Azure/DotNetty#284]
I wonder if is possible nowadays to deploy a UDP server made with dotnetty (I've alrready achieved this!) to azure as a **PAAS** just something similar to a web app deployment on an App Service.

Cheers and congratulations for the fantastic work and project!

**Comment by agnauck** [comment]
You can deploy it to Azure Container Services as PAAS solution. Either as standalone container, or in a cluster using one of the orchestrators Azure offers.
