### ISSUE TITLE
Support for more options to store state per ChannelHandlerContext

### ISSUE THREAD

**Issue by maulik13** [Azure/DotNetty#288]
For example, Netty provides ChannelLocal and attachement to ChannelHandlerContext. Is there any roadmap for adding these to DotNetty?

**Comment by yyjdelete** [comment]
`ChannelLocal` is already removed in netty 4.0, use `AttributeKey` instead.
see also https://github.com/netty/netty/wiki/New-and-noteworthy-in-4.0#attributemap

**Comment by maulik13** [comment]
@yyjdelete Thanks for the update. I looked deeper in DotNetty and do see that AttributeMap is implemented. I will have a go at it.
