### ISSUE TITLE
MQTT and certificates help

### ISSUE THREAD

**Issue by raymondarvidsson** [Azure/DotNetty#292]
Hi,

I really need your help for a few minutes. I´m a C#-developer and have a mission to make calls to Amazon Web Service (AWS) via mqtt. I found this, DotNetty, and is sounds really great!! But it´s not that simple to make the correct call to get it to work. Maby you have some example codes that I can use just to get started.

Thanks!

**Comment by StormHub** [comment]
https://github.com/Azure/DotNetty/blob/dev/test/DotNetty.Tests.End2End/End2EndTests.cs#L119
This test should give you some clue how to set things up.

**Comment by raymondarvidsson** [comment]
Thanks! Will try.

Anyone got this to work with Amazon Web Service? Device Shadow MQTT Topics?
