### ISSUE TITLE
IByteBuffer.ToArray has removed in 0.4.7,need equivalence implement

### ISSUE THREAD

**Issue by windsql** [Azure/DotNetty#307]
when update to DotNetty.Buffers from 0.4.6 to 0.4.7 
The ToArray method has removed from IByteBuffer interface
Is there a method could instead of it.

        protected override void ChannelRead0(IChannelHandlerContext ctx, DatagramPacket packet)
        {
            if (!packet.Content.IsReadable())
            {
                return;
            }

            var message = packet.Content.ToArray(); //It works in 0.4.6,but not work in 0.4.7
            //deal with bytes message
        }

**Comment by StormHub** [comment]
The buffer interface already supports it be default. For example:

var data = new byte[packet.Content.ReadableBytes];
packet.Content.ReadBytes(data);

**Comment by gamemachine** [comment]
Something about it is different.  Using that to get the bytes I start seeing unconsumed data left in the buffer messages.

**Comment by StormHub** [comment]
@gamemachine What do you mean?

**Comment by gamemachine** [comment]
I mean upgrading and changing nothing but one line of code to use what you said to use above to get the byte array, and I get  unconsumed data left in buffer errors.

**Comment by StormHub** [comment]
This is the original implementation, it is not so different anyway 
        public virtual byte[] ToArray()
        {
            int readableBytes = this.ReadableBytes;
            if (readableBytes == 0)
            {
                return ArrayExtensions.ZeroBytes;
            }

            if (this.HasArray)
            {
                return this.Array.Slice(this.ArrayOffset + this.ReaderIndex, readableBytes);
            }

            var bytes = new byte[readableBytes];
            this.GetBytes(this.ReaderIndex, bytes);
            return bytes;
        }
