### ISSUE TITLE
LengthFieldPrepender truncates on 4 length and 8 length

### ISSUE THREAD

**Issue by yourFinger** [Azure/DotNetty#324]
On Encode Method

                 case 4:
                    output.Add(this.byteOrder == ByteOrder.BigEndian
                        ? context.Allocator.Buffer(4).WriteInt((short)length)
                        : context.Allocator.Buffer(4).WriteIntLE((short)length));
                    break;
                case 8:
                    output.Add(this.byteOrder == ByteOrder.BigEndian
                        ? context.Allocator.Buffer(8).WriteLong(length)
                        : context.Allocator.Buffer(8).WriteLongLE(length));
                    break;

length need to long, for support 8 field length?

**Comment by nayato** [comment]
see #321

**Comment by yyjdelete** [comment]
@nayato Seems `WriteInt/WriteIntLE` is not fixed?

**Comment by yourFinger** [comment]
when use 2 field length

On Encode Method 

case 2:
                    if (length >= 65536)
                    {
                        throw new ArgumentException("length of object does not fit into a short integer: " + length);
                    }
                    output.Add(this.byteOrder == ByteOrder.BigEndian 
                        ? context.Allocator.Buffer(2).WriteShort((short)length) 
                        : context.Allocator.Buffer(2).WriteShortLE((short)length));
                    break;

Length need to cast ushort, or short

**Comment by yourFinger** [comment]
@nayato
