### ISSUE TITLE
LengthFieldBasedFrameDecoder problem

### ISSUE THREAD

**Issue by battermaster** [Azure/DotNetty#327]
pipeline.AddLast("frameDecoder", new LengthFieldBasedFrameDecoder(int.MaxValue, 0, 4, 0, 4));
                    pipeline.AddLast("frameEncoder", new LengthFieldPrepender(4));
                    pipeline.AddLast(new ReadHandler());

I use this code.
when I send short length byte[] from server to client, it ok.
but when I send longer byte[] from server, it occurs error, the byte[] length is about 36890 .

the error is in:
DotNetty.Codecs.LengthFieldBasedFrameDecoder.Decode(IChannelHandlerContext context, IByteBuffer input)

**Comment by caozhiyuan** [comment]
LengthFieldPrepender has a lit bug see: https://github.com/Azure/DotNetty/pull/326

**Comment by caozhiyuan** [comment]
Now , You could not Use LengthFieldPrepender , Write len in MsgDecoder

**Comment by battermaster** [comment]
ok, i will try.

**Comment by nayato** [comment]
fixed with #326
