### ISSUE TITLE
Receive or send large data need to set what

### ISSUE THREAD

**Issue by fanliang11** [Azure/DotNetty#341]
dotnetty is very good, so [surging](https://github.com/dotnetcore/surging) is based on the microservice framework of dotnetty, but there is a problem that I decode in the ChannelRead method, decoding over 40KB will throw BUG, I have set LengthFieldBasedFrameDecoder, also need to set other options? Please help me, this problem has troubled me for a long time.
https://github.com/dotnetcore/surging/tree/master/src/Surging.Core/Surging.Core.DotNetty

**Comment by StormHub** [comment]
@fanliang11 do you have some step to reproduce the problem?

**Comment by caozhiyuan** [comment]
@fanliang11  in linux it  my be https://github.com/Azure/DotNetty/pull/336

**Comment by StormHub** [comment]
@caozhiyuan it looks like read issue, not the write outbound.

**Comment by caozhiyuan** [comment]
i  send  40m , in  linux  it  will  block .  and  it  has  bug,  it  may  be  only  send  1m. netty  get  it  send  complete  and  send  next  message. so  server will  parse  error

**Comment by caozhiyuan** [comment]
in  336 pull  has  fixed  it

**Comment by StormHub** [comment]
@caozhiyuan anyway, if you could share some steps to reproduce, that would be a bit more helpful.

**Comment by fanliang11** [comment]
ServerBootstrap added：

```c#
 pipeline.AddLast (new TransportMessageChannelHandlerAdapter (_transportMessageDecoder));
```

TransportMessageChannelHandlerAdapter ：
```c#
class TransportMessageChannelHandlerAdapter : ChannelHandlerAdapter
    {
        private readonly ITransportMessageDecoder _transportMessageDecoder;

        public TransportMessageChannelHandlerAdapter(ITransportMessageDecoder transportMessageDecoder)
        {
            _transportMessageDecoder = transportMessageDecoder;
        }

        #region Overrides of ChannelHandlerAdapter

        public override void ChannelRead(IChannelHandlerContext context, object message)
        {
            var buffer = (IByteBuffer)message;
            var data = new byte[buffer.ReadableBytes];
            buffer.ReadBytes(data);
            **var transportMessage = _transportMessageDecoder.Decode(data);**  //throw BUG
            context.FireChannelRead(transportMessage);
            ReferenceCountUtil.Release(buffer);
        }

        #endregion Overrides of ChannelHandlerAdapter
    }
```
 big data can not be decoded？Is it caused by sending in batches?

**Comment by caozhiyuan** [comment]
windows or linux? @fanliang11

**Comment by fanliang11** [comment]
@caozhiyuan Thank you for your answer，Only test the window to throw a question，I use json.net, messagepack or protobuffer decoding error

**Comment by StormHub** [comment]
@fanliang11 could you also share the data send to the server?

**Comment by StormHub** [comment]
Just by looking at this, have you considered ByteOrder as @caozhiyuan mentioned above. Also, if the data is sent from another platform, there might be ByteOrder watermarks. @fanliang11 could you capture the received data?

**Comment by fanliang11** [comment]
@StormHub thank you for your answor, I was encoded through third-party components to send, and then receive the decoding。

**Comment by caozhiyuan** [comment]
may be this bug? https://github.com/Azure/DotNetty/pull/326/files

**Comment by StormHub** [comment]
@fanliang11 could capture the data causing the error, I am wondering whether it is a byte order issue or not.

**Comment by fanliang11** [comment]
@StormHub I am sorry, reply late,no error was thrown and no complete packet was received resulting in a decoding failure

**Comment by fanliang11** [comment]
@caozhiyuan  Thank you for your answer， Seems to be caused by this problem, when to release nuget。
