### ISSUE TITLE
libuv+IdleStateHandler can not work

### ISSUE THREAD

**Issue by fengbozs** [Azure/DotNetty#343]
libuv+IdleStateHandler can not work
config:
{
  "ssl": "true",
  "port": "8007",
  "libuv": "true"
}

pipeline.AddLast("ping", new IdleStateHandler(10, 10, 0));

 public override void UserEventTriggered(IChannelHandlerContext context, object evt)
        {
            //time out can not trigger 
            if (evt is IdleStateEvent)
            {
        }
}

if libuv config is false,Everything checks out.

**Comment by StormHub** [comment]
Scheduling for the first version of libuv transport was not implemented. The lastest supports scheduling in PR (#332 ) stage at the moment.

**Comment by nayato** [comment]
#332 is merged now.

**Comment by StormHub** [comment]
@fengbozs I can confirm that IdleStateEvent is properly triggered after #332 merged.
