### ISSUE TITLE
LengthFieldPrepender error message wrong

### ISSUE THREAD

**Issue by Iamcaibi** [Azure/DotNetty#349]
LengthFieldPrepender line 121  , can not set to 3,the error message is wrong

**Comment by yyjdelete** [comment]
And the same thing for `LengthFieldBasedFrameDecoder.cs`.

https://github.com/Azure/DotNetty/blob/dev/src/DotNetty.Codecs/LengthFieldBasedFrameDecoder.cs#L419
https://github.com/Azure/DotNetty/blob/dev/src/DotNetty.Codecs/LengthFieldBasedFrameDecoder.cs#L398

Maybe can add support for `Medium`(3)?

**Comment by yyjdelete** [comment]
see also #252
