### ISSUE TITLE
Facing following issues randomly, using Dotnetty 0.4.6 along with Azure Protocol Gateway

### ISSUE THREAD

**Issue by vivekbahl** [Azure/DotNetty#358]
Hi,
We are facing following issues (content pasted in attached jpg files) randomly while running a custom version of the Protocol Gateway, that uses Dotnetty (version 0.4.6.)  -

we are using the following version of SDKs. along with a custome version of [Azure Protocol gateway](https://github.com/Azure/azure-iot-protocol-gateway) –
Microsoft.Azure.Devices 1.2.4
Microsoft.Azure.Devices.Client 1.2.10
Microsoft.Azure.Devices.Shared 1.0.10
Microsoft.ServiceFabric 5.7.198
Microsoft.ServiceFabric.Services 2.7.198
WindowsAzure.Storage 7.2.0
**DotNetty 0.4.6**

These random issues start showing up usually after 2-3 hrs of Protocol Gateway code execution. Please help provide some pointers for understanding the root cause of these.

Thanks,
Vivek Bahl
![image](https://user-images.githubusercontent.com/30576911/36082379-db8e1426-0f76-11e8-9da8-54106b815d58.png)
![image](https://user-images.githubusercontent.com/30576911/36082386-f1f45c98-0f76-11e8-93a3-4969f7f0b4a1.png)
![image](https://user-images.githubusercontent.com/30576911/36082395-ffe451a0-0f76-11e8-9b69-4b612b3f7a33.png)
![image](https://user-images.githubusercontent.com/30576911/36082403-147e1380-0f77-11e8-997a-a5521765d6ad.png)
![image](https://user-images.githubusercontent.com/30576911/36082410-2330ae42-0f77-11e8-9d93-34cdcacf1ccf.png)

**Comment by StormHub** [comment]
Is there any way to repro the issue just by using DotNetty ?

**Comment by nayato** [comment]
I believe it we've sorted it out now.
________________________________

**Comment by vivek2175** [comment]
Thanks Nayato, 
The issues were resolved by updating following in our version of MqttAdapter.cs, in Protocol Gateway code.
1. removed the Usings clauses and converted to try-finally with “message?.Dispose()” statements. As it ensures that message ownership is properly maintained throughout the lifecycle of byte buffers and they are properly disposed in end, by the sendingClient.
2. removed the configureAwait(false) as DotNetty requires, the continuations runs where they originated, and it ensures that all the work for a single connection is done on the same thread.
