### ISSUE TITLE
Is MQTT used as transport, without broker? 

### ISSUE THREAD

**Issue by VladimirAkopyan** [Azure/DotNetty#359]
DotNetty is a bit under-documented. 
Do I understand correctly that the MQTT codec does not perform functions of a broker, that is if client 1 sends a message to a particular topic, it will only be received by the server and not forwarded to any other clients?  
It would be great if there was an example for MQTT.

**Comment by nayato** [comment]
DotNetty only provides means to decode/encode traffic. Building a complete broker or client is out of scope really and properly implementing whole MQTT spec beyond parsing is too much for an example. That said, we've implemented MQTT spec (at least partially) in https://github.com/Azure/azure-iot-protocol-gateway/. It isn't true broker either but it does involve session management and things like maintaining order of ACKs.
