### ISSUE TITLE
How to blocking thread with Console.ReadLine() in WPF application?

### ISSUE THREAD

**Issue by MurrayFan** [Azure/DotNetty#367]
dotNetty's examples are Console Application.There is no problem when using Console.ReadLine() blocking the thread.

I want to add dotNetty to a WPF application as a TCP server,but it just execute to end when I debug using breakpoint.

**Comment by nayato** [comment]
The question is along the lines of "how do I prevent my WPF application from exiting" which has nothing to do with DotNetty really.
