### ISSUE TITLE
How can we enable TLS 1.2 Session resumption support using DotNetty with Azure Protocol Gateway

### ISSUE THREAD

**Issue by vivekbahl** [Azure/DotNetty#368]
Hi,

In our Protocol Gateway implementation, for every connection request that a device sends, PG initiates a full handshake and sends a certificate to device every time. Can we utilize the TLS 1.2 Session resumption
feature, to reduce the time/ resources spent for the TLS handshake, and reduce bandwidth usage at device end.

Does DotNetty provide some support, to enable these requirement. We will need to extract the Client Session Id/Key for storing in some cache store.

Thanks,
Vivek Bahl

**Comment by nayato** [comment]
DotNetty is orthogonal to TLS session resumption. You'd need to check on configuring it for SChannel / SSPI on Windows or OpenSSL on Linux.
