### ISSUE TITLE
No support .net core 2.0

### ISSUE THREAD

**Issue by guopenglun** [Azure/DotNetty#373]
When I build the dotNetty in Visual studio Code ,I got a message of warning
warning NU1701: Package 'Google.ProtocolBuffers 2.4.1.555' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.

**Comment by StormHub** [comment]
Google.ProtocolBuffers is legency protobuf from Google. It is reference by DotNetty as portable library, e.g.  portable-net45+win8.

**Comment by guopenglun** [comment]
thanks for Reply. I updated the Protobuf ,it's work to fine.
