### ISSUE TITLE
Align libuv transport write promise completion with socket transport

### ISSUE THREAD

**Issue by maksimkim** [Azure/DotNetty#376]
For socket based transport write promise can be resolved synchronously:
https://github.com/Azure/DotNetty/blob/e1e93f143b34a15aa883dcd18b101935bdfc9cfe/src/DotNetty.Transport/Channels/Sockets/AbstractSocketByteChannel.cs#L330

...or asynchronously:
https://github.com/Azure/DotNetty/blob/e1e93f143b34a15aa883dcd18b101935bdfc9cfe/src/DotNetty.Transport/Channels/Sockets/AbstractSocketChannel.cs#L213

...but always **after** underlying api (e.g. wsasend in windows case) reported full completion.

For libuv transport write promise **always** resolved when underlying api (uv_write) is successfully **initiated**:
https://github.com/Azure/DotNetty/blob/d31f62a435481c15d47934f8f2622328e55f9133/src/DotNetty.Transport.Libuv/TcpChannel.cs#L162

Concern here is that if uv_write eventually fails (i.e. callbacks with error code), dotnetty write promise will be still resolved successfully.

Suggestion: always complete write promise  for **successfully initiated** uv_write call upon completion. Presumably here:
https://github.com/Azure/DotNetty/blob/d31f62a435481c15d47934f8f2622328e55f9133/src/DotNetty.Transport.Libuv/Native/WriteRequest.cs#L215

**Comment by maksimkim** [comment]
@nayato, we discussed that with @StormHub and agreed it's doable. Need 3rd opinion.

**Comment by nayato** [comment]
well, we sure don't want to report on smth that is not completed as if it is. On the other hand, successful write completion only means that your bytes were successfully accepted to send buffer i.e. it doesn't guarantee bytes were actually delivered. From that perspective putting libuv's write ack into the same bucket is not a big deal. On the other hand, if we write and it completes with an error that we don't get, we're missing an opportunity to close channel on failed write...

**Comment by StormHub** [comment]
If libuv async writes fail, the callback errors are reported by channel ExceptionCaught at the moment.

**Comment by StormHub** [comment]
@maksimkim raised an issue regarding buffers made feel a bit concerned 
for example:
await ctx.WriteAndFlushAsync(mybuffer);
// buffer sent completes, now release the buffer or do whatever
myBuffer.Release(); 

In libuv, this is not true before the write callback is invoked.

**Comment by nayato** [comment]
well, that is a reasonable concern :)

**Comment by StormHub** [comment]
@nayato @maksimkim I thought so. If you do something like that right after write async call returns and just before the callback is invoked, bad things would happen.
