### ISSUE TITLE
port LoggingHandler

### ISSUE THREAD

**Issue by nayato** [Azure/DotNetty#38]
`LoggingHandler` is essential for debugging any complex pipeline processing and is a great tool for learning mechanics of netty.

**Comment by sudheer594** [comment]
@nayato ,

I have ported the LoggingHandler code. please review

**Comment by nayato** [comment]
Hey @sudheer594! Thanks for taking on that! Looks pretty good. I've posted a few comments, mostly formatting issues. Do you happen to have ReSharper? we've put up team-shared settings for it so it would know the style we use + you could easily reformat both files using Cleanup Code feature. Let me know, if you don't have it so we can figure something out.

**Comment by sudheer594** [comment]
@nayato, I have Resharper, will do the  changes. Thanks.

**Comment by sudheer594** [comment]
Hey @nayato , I have done the changes you have suggested. please take a look.

**Comment by nayato** [comment]
yep, looks good. Now the fun part: can you please squash your commits and post a proper pull request?

**Comment by nayato** [comment]
also, pls sign the CLA: https://cla.azure.com/

**Comment by sudheer594** [comment]
@nayato, i have created  pull request with changes.please review

**Comment by nayato** [comment]
Great to hear! Now if only you could sign the CLA (https://cla.azure.com/)...

**Comment by sudheer594** [comment]
signed it a week ago, got a confirmation to mail.not sure why it is not updated :(

**Comment by nayato** [comment]
Something's probably misconfigured for CLA management. We'll sort it out and I'll merge tomorrow morning PST.

**Comment by nayato** [comment]
@sudheer594, thanks for pulling this through!
