### ISSUE TITLE
SSL connection BUG?

### ISSUE THREAD

**Issue by guopenglun** [Azure/DotNetty#381]
I try to establish an SSL connection on port 12345
I use wireShark&npcap to Monitor the local network.
I Saw the  Server and client communicate using the TCP protocol
But ,when I use the port of 443,
they show protocol is TLSv1.2.
it's a bug?

**Comment by yyjdelete** [comment]
By default, wireshark only decode some wellknown port as SSL.
You can right click on one package in wireshark, then click `Decode As...`, and add TCP port 12345 as SSL.

**Comment by guopenglun** [comment]
thanks for your reply.
