### ISSUE TITLE
how to release the HeapArena

### ISSUE THREAD

**Issue by guopenglun** [Azure/DotNetty#385]
Hi,
On server configure .I add the item ：
`.Option(ChannelOption.Allocator, PooledByteBufferAllocator.Default)`
 but ,when Client disconnect .the heapMemory is Not released.
After that I connected again.This memory is not reused

**Comment by StormHub** [comment]
I am not sure what you are trying to achieve? The HeapArena is supposed to last for the life time of the application and definitely shared for all channels in the server.

**Comment by guopenglun** [comment]
thank you, It's my mistake.
I use the Visual studio 2017 Diagnostic tools.
their show the Memory usage is not Physical memory usage.

**Comment by guopenglun** [comment]
But  If you print debugging information。
 
 ` var allocator = channel.Allocator as PooledByteBufferAllocator;
Console.WriteLine($"{allocator.Metric.UsedHeapMemory}"); `

the UsedHeapMemory value continued growth when Clients connect repeatedly。
