### ISSUE TITLE
RedisDecoder.cs got an out_of_memory exception

### ISSUE THREAD

**Issue by vivid216** [Azure/DotNetty#387]
sometimes my app got an out of memory exception when test redis program.  when i debug the function DecodeBulkStringContent here

`
bool DecodeBulkStringContent(IByteBuffer byteBuffer, ICollection<object> output)

        {
            .......
            // chunked write.

            int toRead = Math.Min(this.remainingBulkLength, readableBytes);

            this.remainingBulkLength -= toRead;

            IByteBuffer buffer = byteBuffer.ReadSlice(toRead);

            output.Add(new BulkStringRedisContent((IByteBuffer)buffer.Retain()));

            return true;

        }`
   
  Variable  remainingBulkLength=0, but the readableBytes=1,  and got a dead loop until out of memory, and now test byteBuffer.readByte() = 13,   i don't know what happened,  redis server send an wrong message or other ?

**Comment by StormHub** [comment]
Do you have some sort of message logging to see what came out of the redis?
I have been using Redis for quite a while, haven't seen this so far.

**Comment by caozhiyuan** [comment]
@StormHub last time i say it on gitter . change the code same to java will ok . 

if (readableBytes == 0 || this.remainingBulkLength == 0 && readableBytes < RedisConstants.EndOfLineLength)

**Comment by vivid216** [comment]
the test case will cause the error.  

`DotNetty.Transport.Channels.Embedded.EmbeddedChannel embeddedChannel
                    = new DotNetty.Transport.Channels.Embedded.EmbeddedChannel(
                        new DotNetty.Codecs.Redis.RedisDecoder(),
                         new DotNetty.Codecs.Redis.RedisBulkStringAggregator(),
                            new DotNetty.Codecs.Redis.RedisArrayAggregator());


                string test = "*3\r\n$7\r\nmessage\r\n$16\r\nTd:demo_response\r\n$3\r\nabc\r";
                embeddedChannel.WriteInbound(test.Buffer());
                var r = embeddedChannel.ReadInbound<DotNetty.Codecs.Redis.Messages.ArrayRedisMessage>();
                embeddedChannel.WriteInbound("\n".Buffer());
                var r2 = embeddedChannel.ReadInbound<DotNetty.Codecs.Redis.Messages.ArrayRedisMessage>();`
