### ISSUE TITLE
SkipAttribute

### ISSUE THREAD

**Issue by wjkhappy14** [Azure/DotNetty#406]
**[Skip]**
        public virtual void ChannelRegistered(IChannelHandlerContext context) => context.FireChannelRegistered();
where  and when to add  Skip  attribute  ?

**Comment by nayato** [comment]
Don't add it anywhere. It is meant as means of distinguishing by pipeline's mechanism whether there's non-trivial behavior in given handler for the given event while propagating it through pipeline.
