### ISSUE TITLE
ChannelFuture

### ISSUE THREAD

**Issue by wjkhappy14** [Azure/DotNetty#407]
no file named ChannelFuture.cs or similar？
if so，  how to do the same logic as Java Netty's ChannelFuture ?

anyone knows why or how ?

**Comment by onatm** [comment]
it's because of the difference of async. i/o in java and c#.

check https://github.com/Azure/DotNetty/wiki/Porting-status-and-notes#by-components

**Comment by wjkhappy14** [comment]
got it ,thanks !
