### ISSUE TITLE
What's  different  between  xxxxxHandler and  xxxxAdapter?

### ISSUE THREAD

**Issue by wjkhappy14** [Azure/DotNetty#408]
I want to  know  when  i  use  xxxHandler  and  when i  use  xxxxAdapter

I  am a new beginner   for Netty ,so  maybe  it's a  simple  question for  you .but i need to know cleanly !

thanks !

**Comment by nayato** [comment]
IChannelHandler - interface for channel handlers. ChannelHandlerAdapter - base impl for a channel handler.
