### ISSUE TITLE
memory leak?

### ISSUE THREAD

**Issue by kissstudio** [Azure/DotNetty#409]
project: examples/HttpServer 
when use chrome F12 network tab and press F5 to visit path / or /json or /plaintext with high frequncy, even response is 404, the memory usage of dotnet process is keep increasing.

after 3*5K requests , memory usage is up to 100MB and still increasing.
![image](https://user-images.githubusercontent.com/2771647/42383754-c9e0d2c0-816a-11e8-980c-fc576d916834.png)

test target is release version of the project on windows 10

**Comment by Flyoutwithme** [comment]
前段时间我使用时也遇到了，我刚开始也以为是内存泄露。。然后捣鼓了不少时间。。。
配置Bootstrap时试试加上配置
`_bootStrap.Option(ChannelOption.Allocator, new UnpooledByteBufferAllocator());`
默认好像是使用了更高性能的缓冲池的，不过相对的内存使用会大一些。

**Comment by caozhiyuan** [comment]
you can use dump tool and vs2017 analysis memory info. 
https://blog.csdn.net/zhuankeshumo/article/details/80212454  use vs2017 open dump file

**Comment by fanliang11** [comment]
Personally think it should be your problem, [surging](http://github.com/dotnetcore/surging) uses dotnetty as the underlying communication, including tcp and http protocols, all memory is only about 40MB

![image](https://user-images.githubusercontent.com/17928535/42416357-d2a7228a-829e-11e8-8bd2-7e7ec34d9cca.png)

**Comment by kissstudio** [comment]
@Flyoutwithme 

tried the option. the same.

**Comment by kissstudio** [comment]
@fanliang11 

how many requests processed? 
try more requests like 20k.

**Comment by fanliang11** [comment]
16 thread tests, stable at around 40MB

**Comment by yyjdelete** [comment]
@kissstudio 
Edit the `.csproj`, change `ServerGarbageCollection` from `true` to `false`, and rebuild if you want more resonable memory usage.

@StormHub 
I see an `NullReferenceException` is keeping throw for every 404 request and `libuv=true` at 
https://github.com/Azure/DotNetty/blob/580bde0/src/DotNetty.Transport.Libuv/NativeChannel.cs#L348
when try to access with chrome(or some other client), can you have a look for this?

**Comment by Flyoutwithme** [comment]
好吧，我是在其它项目遇到内存暴涨的问题的，我以为这个也是。
不过内存并没有持续暴涨，我测试500万次请求内存也一直维持在一个相对稳定的水平。

另外楼上的方法是正确的。

**Comment by StormHub** [comment]
@yyjdelete server GC consumes memory pool a bit more aggressively and well suited for lower latency. e.g. trade off between perf and resources. 
For the 404 error? could you share how to reproduce it?

**Comment by kissstudio** [comment]
@StormHub 
the default path / is 404
`default:
                    var response = new DefaultFullHttpResponse(HttpVersion.Http11, HttpResponseStatus.NotFound, Unpooled.Empty, false);
                    ctx.WriteAndFlushAsync(response);
                    ctx.CloseAsync();
                    break;`

**Comment by kissstudio** [comment]
@caozhiyuan  vs debug snapshot can see it directy. the ouput is too  difficult for me to understand

**Comment by kissstudio** [comment]
Also tried mina.NET, memory usage is not increase what ever how many same requests processed.

**Comment by kissstudio** [comment]
PS, the test result is the same for me using libuv or not.

**Comment by yyjdelete** [comment]
@kissstudio 
Can't reproduce that.
Do you really see `Server garbage collection: False` in the console? If not, please clean the project and rebuild again
![image](https://user-images.githubusercontent.com/1819074/42417881-d13f2b7c-82c6-11e8-95a2-a326ab4e2b9f.png)

**Comment by kissstudio** [comment]
how to set？@yyjdelete

**Comment by yyjdelete** [comment]
@kissstudio 
1. Right click `HttpServer` project in VS, `Edit HttpServer.csproj`, replace, right click again, `Rebuild` or `Clean` (instead of `Build` or `Run`)
2. Or edit `HttpServer.csproj` with any editor, replace, remove `bin` and `obj` folder, and build again.
3. Or open the output folder, find `HttpServer.runtimeconfig.json`, and add the below config or replace exists one.
```json
,
    "configProperties": {
      "System.GC.Server": true
    }
```

**Comment by kissstudio** [comment]
thanks @yyjdelete  i rebuild the solution this time and the problem solved.

but the server gc did not easy to undersand.
