### ISSUE TITLE
won't slice of span<T> be a better solution

### ISSUE THREAD

**Issue by erwan-joly** [Azure/DotNetty#411]
wouldn't slice of span<T> be a faster/better solution for this slicing system ?https://github.com/Azure/DotNetty/blob/f227f95966c6380aee8d07c6f786873e974e3f8a/src/DotNetty.Common/Utilities/ArrayExtensions.cs

**Comment by nayato** [comment]
Considering
a) this piece was written 3 years ago
b) Spans are not in .NET Standard yet and will never be in .NET Standard v1.3
comment is misplaced. Now focusing on point b) specifically, it would be a breaking change or an uncontrollable spread of `#if`s across the code.
We are aware of Spans/Memory and its benefits, it is just not there yet in terms of adoption.

**Comment by simonlaroche** [comment]
s

**Comment by erwan-joly** [comment]
The question was mostly to know if it would be better and in that case I would have done it and PR. I know it was not here 3 years ago. I haven’t thought about the net standard version.
My question was mostly to know if it would be better and won’t get any breaking change with span. To avoid doing a useless piece of work.
Seems the answer is yes it would be better but it would be a breaking change so don’t do it.
