### ISSUE TITLE
ReadTimeoutHandler and IdleStateHandler.  Always trigger the read timeout bug

### ISSUE THREAD

**Issue by ludycool** [Azure/DotNetty#416]
Always trigger readtimeout, even if it's sending data all the time.
`pipeline.AddLast(new ReadTimeoutHandler(6); `

or
` pipeline.AddLast(new IdleStateHandler(0, 0, 6));
 pipeline.AddLast(new ChannelInboundHandlerAdapter());
`
`  class ChannelInboundHandlerAdapter : ChannelHandlerAdapter
    {

        public override void UserEventTriggered(IChannelHandlerContext ctx, object evt)
        {

            if (evt is IdleStateEvent)
            {
                IdleStateEvent evv = (IdleStateEvent)evt;
                if (evv.State == IdleState.AllIdle)
                {
                    Console.WriteLine("all time out：" + DateTime.Now.ToString("mm:ss")+ "id:"+ ctx.Channel.Id);
                }
                else if (evv.State == IdleState.WriterIdle)
                {
                    Console.WriteLine("writer time out：" + DateTime.Now.ToString("mm:ss") + "id:" + ctx.Channel.Id);
                }
                else if (evv.State == IdleState.ReaderIdle)
                {
                    Console.WriteLine("read time out：" + DateTime.Now.ToString("mm:ss") + "id:" + ctx.Channel.Id);

                   // ctx.CloseAsync();
                }
            }
            else
            {
                base.UserEventTriggered(ctx, evt);
            }
        }
    }`

**Comment by chenderong** [comment]
You should put it in the first pipeline

**Comment by ludycool** [comment]
> You should put it in the first pipeline

thank you . I found this problem two months ago
