### ISSUE TITLE
IByteBuffer readUnsignedByte

### ISSUE THREAD

**Issue by yeooooo** [Azure/DotNetty#420]
Why not exist readUnsignedByte method in the IByteBuffer class? If want it,what can i do?

**Comment by erwan-joly** [comment]
ubyte doesnt exist byte(0-255) is already unsigned. if you want a signed byte it's sbyte (-128 to 127). Network transport bytes from 0 to 255 so it doesn't make any sense to use a sbyte.

**Comment by yeooooo** [comment]
my transport data is hex,I need read a sbyte.I use (int)(sbyte)buf.ReadByte() insteaded now.
