### ISSUE TITLE
Udp Channel is not receiving any messages

### ISSUE THREAD

**Issue by yulianoifa-mobius** [Azure/DotNetty#430]
Hi
I am creating the udp client using following code :
```
                bootstrap = new Bootstrap();
                loopGroup = new MultithreadEventLoopGroup(workerThreads);
                bootstrap.Group(loopGroup);
                bootstrap.Channel<SocketDatagramChannel>();
                bootstrap.Handler(new ActionChannelInitializer<SocketDatagramChannel>(channel =>
                {
                    IChannelPipeline pipeline = channel.Pipeline;
                    pipeline.AddLast("handler", new SNHandler(listener));
                    pipeline.AddLast(new SNEncoder(channel));
                    pipeline.AddLast(new ExceptionHandler());
                }));

                bootstrap.RemoteAddress(address);

                try
                {
                    Task<IChannel> task = bootstrap.ConnectAsync();
                    task.GetAwaiter().OnCompleted(() =>
                    {
                        try
                        {
                            channel = task.Result;
                        }
                        catch (Exception)
                        {                            
                            listener.ConnectFailed();
                            return;
                        }

                        if (channel != null)
                            listener.Connected();
                        else
                            listener.ConnectFailed();
                    });
                }
                catch (Exception)
                {
                    return false;
                }
```

the SNHandler is defined as 
`public class SNHandler : SimpleChannelInboundHandler<DatagramPacket>`
However ChannelRead0 is never called on the channel.
I have also tried to implement SNHandler : ChannelHandlerAdapter and use ChannelRead with no luck.
ChannelInactive is working properly on same class. 
The packets are received from the same address , channel is connecting to.

**Comment by StormHub** [comment]
hum, as far as I know of, you have to bind the client address to receive packages, 
e.g.
https://github.com/Azure/DotNetty/blob/dev/examples/QuoteOfTheMoment.Client/Program.cs#L36

**Comment by yulianoifa-mobius** [comment]
> hum, as far as I know of, you have to bind the client address to receive packages,
> e.g.
> https://github.com/Azure/DotNetty/blob/dev/examples/QuoteOfTheMoment.Client/Program.cs#L36

There is huge difference between bind and connect. When binding you actually allow packets to be received from any address, while connecting you only allow packets to be received from specific destination.
However the connect is not working as expected

**Comment by yulianoifa-mobius** [comment]
I have found a solution.
`Task<IChannel> task = bootstrap.BindAsync(IPEndPoint.MinPort);
                    task.GetAwaiter().OnCompleted(() =>
                    {
                        try
                        {
                            channel = task.Result;
                            Task connectTask = channel.ConnectAsync(address);
                            connectTask.GetAwaiter().OnCompleted(() =>
                            {
                                if (channel != null)
                                    listener.Connected();
                                else
                                    listener.ConnectFailed();
                            });
                        }
                        catch (Exception)
                        {                            
                            listener.ConnectFailed();
                            return;
                        }                        
                    });`

not clear why connect does not do bind in this case, however it works with this sequence
