### ISSUE TITLE
Messages are not correctly received

### ISSUE THREAD

**Issue by BlowaXD** [Azure/DotNetty#450]
Hi,

I'm using DotNetty instead of own made network wrapper for my actual project.
I got one important issue on my project

Here is the bootstrap code i'm using to init my server
![image](https://user-images.githubusercontent.com/16936368/50019974-848f3d00-000f-11e9-93fe-4da1a5281dc6.png)

Here is my ChannelInitializer 
![image](https://user-images.githubusercontent.com/16936368/50019766-d84d5680-000e-11e9-8fff-f559e3987675.png)

Here is the error (the ÿ should be there to split two different packets)
https://cdn.discordapp.com/attachments/223116487869595649/523185832065237012/unknown.png
![image](https://user-images.githubusercontent.com/16936368/50019871-2d896800-000f-11e9-8b88-fccd255afd67.png)
This error does not occur on another project where the received bytes are Enqueued and then Dequeued in a defined packet queue.

The error only occurs when someone is SPAMMING lot of packets (much faster than an human could do by normally playing the game) for like more than 5 seconds. 
An exception is thrown and then the socket get closed.

I hope that there is already something like that provided by netty but I couldn't find (maybe bing is not accurate enough in China)
- Am I doing something wrong with my MessageToMessageDecoder / Netty Configuration ?

If you need more details, I'm up to answer !

Thanks by advance,
Blowa.

**Comment by 0Lucifer0** [comment]
Wondering if it doesn’t just need some DelimiterBasedFrameDecoder or a isReadable night the packet itself ;) I think the most important part here is the encoder decoder.
