### ISSUE TITLE
dotNetty eats 99% of CPU

### ISSUE THREAD

**Issue by xiazhaozhao** [Azure/DotNetty#486]
Environment
OS: Window server 2012 R2
Description
Please help.

ServerBootstrap bootstrap = new ServerBootstrap();
                bootstrap
                    .Group(bossGroup, workerGroup)
                    .Channel<TcpServerSocketChannel>()
                    .Option(ChannelOption.SoBacklog, 100)
                    //.Option(ChannelOption.)
                    .ChildHandler(new ActionChannelInitializer<ISocketChannel>(channel =>
                    {
                        IChannelPipeline pipeline = channel.Pipeline;
                        if (tlsCertificate != null)
                        {
                            pipeline.AddLast(TlsHandler.Server(tlsCertificate));
                        }
                        pipeline.AddLast(new IdleStateHandler(120, 0, 0));//第一个参数为读，第二个为写，第三个为读写全部
                        pipeline.AddLast(new CommunicationEncoder());
                        pipeline.AddLast(new CommunicationDecoder(0x76, 2048, 22));
                        pipeline.AddLast(new CmdServerHandler(_clientsList,redisClient));
                    }));

**Comment by stratosblue** [comment]
You can analysis it yourself with visualstudio diagnostic tools.
step1. enable CPU analysis
![1](https://user-images.githubusercontent.com/20887303/60227714-e4ba4200-98c2-11e9-83ec-1dc2e4ef17c9.png)

step2. run and break it
![2](https://user-images.githubusercontent.com/20887303/60227747-04ea0100-98c3-11e9-9dc2-2d9fe3cb159b.png)

step3. select time period and find what ate cpu
![3](https://user-images.githubusercontent.com/20887303/60227815-411d6180-98c3-11e9-9291-ab170af0b21a.png)

**Comment by nayato** [comment]
I'd suggest looking through your own code. The setup for dotnetty from what is shown is ok. Feel free to re-open if you see any more specific evidence it is dotnetty's issue. Meanwhile I'd suggest checking PerfView for performance analysis.
