### ISSUE TITLE
chunkedWriteHandler does not work when use chunkedStream(fileStream)

### ISSUE THREAD

**Issue by cocosip** [Azure/DotNetty#492]
I use chunkedWriteHandler to send file.
```c#
 var stream = new ChunkedStream(request.Stream, 1024 * 1024 * 10);
 _channel.WriteAndFlushAsync(stream).Wait();
```
when the request.Stream is `MemoryStream` , it works well. 
but when the request.Stream is `FileStream` , it seem not work.

**Comment by cocosip** [comment]
I know the cause of the problem.
In `chunkedStream`  ,the method `public IByteBuffer ReadChunk(IByteBufferAllocator allocator)`  have a code:
```c#
int count = buffer.SetBytesAsync(buffer.WriterIndex, this.input, readChunkSize, CancellationToken.None).Result;
```
in buffer implements such as  `PooledHeapByteBuffer`, `CompositeByteBuffer`, `UnpooledHeapByteBuffer`, `UnpooledHeapByteBuffer`, the method `SetBytesAsync` is `async` and it not use `ConfigureAwait(false)` ,so it cause **deadlock**

**Comment by caozhiyuan** [comment]
@StormHub pelease check chunkedStream  buffer.SetBytesAsync .Result
