### ISSUE TITLE
When should I use libuv

### ISSUE THREAD

**Issue by yedajiang44** [Azure/DotNetty#539]
See this code in the example
```c#
IEventLoopGroup group;
            IEventLoopGroup workGroup;
            if (useLibuv)
            {
                var dispatcher = new DispatcherEventLoopGroup();
                group = dispatcher;
                workGroup = new WorkerEventLoopGroup(dispatcher);
            }
            else
            {
                group = new MultithreadEventLoopGroup(1);
                workGroup = new MultithreadEventLoopGroup();
            }
```
How should I choose whether to use libuv, whether it is related to the system platform (win or linux or mac) or the specific scene

**Comment by egmkang** [comment]
https://developers.redhat.com/blog/2018/07/24/improv-net-core-kestrel-performance-linux/


![image](https://user-images.githubusercontent.com/65175/95307160-e0991480-08ba-11eb-8a9e-f969eab396a5.png)
