### ISSUE TITLE
DotNetty v0.7.0 enforces .NET 5

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/DotNetty#564]
DotNetty v0.7.0 is breaking semantic versioning since it enforces .NET 5 (which is not LTS) and is breaking clients such as Microsoft Azure IoT SDK for .NET

Relates to https://github.com/Azure/azure-iot-sdk-csharp/issues/2149

**Comment by nayato** [comment]
When dealing with 0.x versions, per semver, x changing means breaking change. There are a couple breaking changes, hence it is 0.7 and not 0.6.1 for instance.
DotNetty 0.7 supports .NET 4.7.2 and .NET Standard 2.0. It stopped supporting .NET versions below 4.7.2 to get rid of conflicting dependencies that basically do not let one use it with more modern versions. I don't see how DotNetty's new release in itself is a problem.

**Comment by tomkerkhove** [comment]
It is because for .NET Core projects it is enforcing .NET 5 as per this change https://github.com/Azure/DotNetty/commit/1cdaadbfaad12046442426bb2d9655c3b2a1390b

This is what clients get:
```
NU1107: Version conflict detected for Microsoft.Extensions.Logging. Install/reference Microsoft.Extensions.Logging 5.0.0 directly to project SampleProject to resolve this issue. 
 SampleProject -> Microsoft.Azure.Devices.Client 1.38.0 -> DotNetty.Handlers 0.7.0 -> DotNetty.Common 0.7.0 -> Microsoft.Extensions.Logging (>= 5.0.0) 
 SampleProject -> Microsoft.Extensions.Logging (>= 3.1.14 && < 5.0.0).
```

With regards to this:
> When dealing with 0.x versions, per semver, x changing means breaking change. There are a couple breaking changes, hence it is 0.7 and not 0.6.1 for instance.
> DotNetty 0.7 supports .NET 4.7.2 and .NET Standard 2.0. It stopped supporting .NET versions below 4.7.2 to get rid of conflicting dependencies that basically do not let one use it with more modern versions. I don't see how DotNetty's new release in itself is a problem.

Today I learned:

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.
> 
> Version 1.0.0 defines the public API. The way in which the version number is incremented after this release is dependent on this public API and how it changes.
> 
> Patch version Z (x.y.Z | x > 0) MUST be incremented if only backwards compatible bug fixes are introduced. A bug fix is defined as an internal change that fixes incorrect behavior.
> 
> Minor version Y (x.Y.z | x > 0) MUST be incremented if new, backwards compatible functionality is introduced to the public API. It MUST be incremented if any public API functionality is marked as deprecated. It MAY be incremented if substantial new functionality or improvements are introduced within the private code. It MAY include patch level changes. Patch version MUST be reset to 0 when minor version is incremented.

Thanks for sharing.

**Comment by nayato** [comment]
I'd suggest to check dependencies on nuget page for those packages. E.g. https://www.nuget.org/packages/System.Runtime.CompilerServices.Unsafe/ supports .net core 2.0+. `5.0.0` does not refer to version of framework it requires.

**Comment by tomkerkhove** [comment]
DotNetty does unfortunately:
![image](https://user-images.githubusercontent.com/4345663/129780514-a1ad224d-c8a4-44f6-88a8-fa32cf8dfbb0.png)

**Comment by nayato** [comment]
if you now go to Microsoft.Extensions.Logging, you'll see that version 5.0.0 is compatible with .NET Core 2.0+

**Comment by yyjdelete** [comment]
@nayato Infact, due to some hard limit of package version in netcore2.1, it's not really compatible with `aspnetcoreapp2.1`(it works with 3.1+)

See `Dependencies` in 
https://www.nuget.org/packages/Microsoft.AspNetCore.App/2.1.29

**Comment by tomkerkhove** [comment]
Fair point, my bad. People tend to not use .NET packages that are 5.x while still on 3.x but you are correct.
