### ISSUE TITLE
Expose SslStream configuration options used in TlsHandler

### ISSUE THREAD

**Issue by whizlingo** [Azure/DotNetty#60]
i am trying to host dot netty Client and server. When i monitor the tls traffic going on wireshark , i see the protocol set to tls 1.0 is their a way i can configure  to do ssl handshake on tls 1.2

**Comment by nayato** [comment]
Unfortunately there is no way right now. To do that we'd need to pass a set of supported protocols here: https://github.com/Azure/DotNetty/blob/dev/src/DotNetty.Handlers/Tls/TlsHandler.cs#L250
The way TLS support is integrated right now is less than ideal and we plan to change that soon providing easier customization by accepting object that embeds `SslStream` integration. That way users will be able to override the defaults by inheriting or replacing such an object.

**Comment by whizlingo** [comment]
Thanks Max , that's exactly what I figured out yesterday, changed it to pass protocols similar to how we do for client and was able to see the desired results in wire shark. Thanks for your inputs.

Sent via Phone...
