### ISSUE TITLE
DotNetty not sending data to server

### ISSUE THREAD

**Issue by hYdos** [Azure/DotNetty#609]
I'm working on a DotNetty Client and a Netty Server for some quick Java to C# communication and I ran into an issue where DotNetty is not encoding or sending any data at all to my server. I have confirmed the server side works by writing a simple netty client quickly. 

Here is a copy of my code:
The main networking stuff:
https://github.com/hYdos/IgTools/blob/master/RenderClient/RenderClient.cs

The stuff using that class:
https://github.com/hYdos/IgTools/blob/master/AlchemyEditor/Program.cs

**Comment by fanliang11** [comment]
Hello,
          I have a deep understanding of Netty and have developed a microservice framework for communication between Java and C #. However, if you use a Message Encoder in your code, it does not support cross language communication. When the client sends an encoded message and decodes it on the server, it causes an error. Therefore, if you believe that you did not receive the message, it is actually a decoding error. For the encoding and decoding of messages between different languages, We need to implement ChannelHandlerAdapter to customize encoding and decoding, which can be done using Java's gson, protobuf, and C #'s Newtonsoft, protobuf。

**Comment by hYdos** [comment]
The thing is My breakpoints in my Java pipeline are not hit at all. I have confirmed this should be at least be getting hit because i connected with my browser and even doing this caused my breakpoint to be hit. I even breakpointed in the C# encoder and nothing even reaches that stage. Thanks for pointing out that issue, But i still believe there is another issue hidden somewhere.

**Comment by yyjdelete** [comment]
@hYdos You are try to send a `Packet`, but your `MessageEncoder` only works with `ChannelMessage`.

**Comment by hYdos** [comment]
> @hYdos You are try to send a `Packet`, but your `MessageEncoder` only works with `ChannelMessage`.

fixed that my bad but still it never hit the encoder after that.
![image](https://github.com/Azure/DotNetty/assets/25501603/e45ba327-0cad-4e0d-9c72-6d0f07b3d310)
breakpoint is here ^

**Comment by yyjdelete** [comment]
@hYdos
https://gist.github.com/yyjdelete/4d32fc669d583ba908c0ce01538c576f

**Comment by hYdos** [comment]
something you did made the breakpoint get hit. Thank you so much! what was wrong?
