### ISSUE TITLE
Setting up both TLS and non TLS Server Bootstrap.

### ISSUE THREAD

**Issue by whizlingo** [Azure/DotNetty#61]
Is there any way to use Server Bootstrap with both TLS and non TLS Port(basically one with TLS handler and one without) ?. I feel that creating a separate server boot strap will lead to double initialization of all the handlers in the pipeline. Please suggest. 

Also , let me know if raising an issue here is the appropriate way of asking queries on the project ? :)

**Comment by nayato** [comment]
Usually TLS and non-TLS traffic come on different ports. You can write channel initializer so that if port is for TLS, TlsHandler is added to pipeline. Like [here](https://github.com/Azure/DotNetty/blob/dev/examples/Echo.Server/Program.cs#L40) but check `((IPEndpoint)ch.LocalAddress).Port`

**Comment by nayato** [comment]
If you do want to accept both TLS and non-TLS traffic on the same port, that's possible too but you'd need to manually implement an IChannelHandler that would figure out if first message is part of the TLS handshake or is an unencrypted packet, remove itself, add TlsHandler if message is for TLS, forward this first message down the pipeline.

**Comment by whizlingo** [comment]
Many thanks i able to get it working !
