### ISSUE TITLE
Nightly builds are not discoverable from docs

### ISSUE THREAD

**Issue by sant0ro** [Azure/DotNetty#77]
will be Nuget updated with lastest commits? Or i need manually clone and build to test lastest environments?

Regarding that DotNetty isn't compatible yet with Travis CI, also the Project create incompatibilities if change from Nuget to Local Builded. Since need Import in VS Root the .dlls

(I'm really wanting to test new commit builds and see if some bugs disappeared..)

Thanks!

**Comment by chester89** [comment]
Why is it not compatible with Travis?

**Comment by sant0ro** [comment]
MSBuild...

**Comment by sant0ro** [comment]
(Remembering Travis C# Port still in BETA...) Since uses Mono.. DotNetty doesn't work really as well with Mono..

**Comment by nayato** [comment]
nightly builds are posted here: https://www.myget.org/F/dotnetty/api/v2/
Let's keep this issue open until we get to update the docs.
Regarding Travis: we considered building there and yes, it only supports Mono so no go. Is there anything else besides nightly builds you think is missing in current CI setup?
Also, completing support for .NET Core may open other options for CI. We'll reconvene on that once it is in.

**Comment by sant0ro** [comment]
About Travis Setup, recommend to see directly what happens:
<pre>
script:
  - xbuild YOURSLN /p:Configuration=Release /p:Platform="x64"
install:
  - nuget restore YOURSLN -Verbosity detailed
  - nuget update YOURSLN -Verbosity detailed
</pre>

DotNetty is only WORKING to be compiled as THIRD PARTY NuGET Package. That means, your Project will be sucessfully Traced by Travis if you're trying to Include DotNetty as a Package.
Using Travis to BUILD DotNetty will doesn't work, since Travis uses Mono, and DotNetty isn't CLS Ready, as far i know some specific variables are only able for Windows, (some MSBuild protocols)

Also Travis uses x64 machines, you can force xbuild to use x64 Platform for Building.

Remember that XBUILD is a port of MSBUILD, hasn't every functionalities.

I'm only clearing some things out here..

**Comment by sant0ro** [comment]
You can also try using
<pre>
mono:
  - latest
</pre>

But as far i know latest versions of Mono are experimental for .NET 4.6.X

**Comment by Aaronontheweb** [comment]
@sant0ro rather than switch build servers (which doesn't seem relevant to this) why not just send a PR to the docs with a link to the nightly MyGet feed?

**Comment by sant0ro** [comment]
Sorry, but idk what is "MyGet feed"

**Comment by nayato** [comment]
I've posted a link to MyGet above where nightly builds of DotNetty go. No worries, I'll update docs once I get a chance to catch a breath here. Would need words for both nuget and myget so that ppl don't think myget is a go to place for builds in general.
